### ISSUE TITLE
cron perf tests failing

### ISSUE THREAD

**Issue by jpchen** [uber/pyro#1045]
our cron job which runs the perf tests have failed the last [4 out of 5 times](https://travis-ci.org/uber/pyro/builds). from one job:
```
Performance has regressed:
	benchmark[PoissonGamma::reparam=False_Trace] (0001) - Field 'min' has failed PercentageRegressionCheck: 17.686598386 > 15.000000000
	benchmark[PoissonGamma::reparam=False_TraceGraph] (0001) - Field 'min' has failed PercentageRegressionCheck: 19.626317156 > 15.000000000
```
might be a case of just loosening the assertions but it might be worth taking a look at

**Comment by neerajprad** [comment]
It's mostly noise :( I think we should just loosen the thresholds, running these perf tests on VMs is going to be noisy. Will resurrect my previous PR.
