### ISSUE TITLE
Tests giving incorrect results on CUDA

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1051]
I am trying to fix tests that don't work with CUDA..e.g. by adjusting precision, changing functions that do not have CUDA implementations, etc. 

Following is a working list of tests that are giving incorrect results, and which seem to have deeper issues:
 - [ ] #1057 `tests/contrib/gp/test_models.py::test_inference` - Results are too inaccurate. cc.@fehiepsi

**Comment by fehiepsi** [comment]
I will look into this problem now.

**Comment by neerajprad** [comment]
Thanks, @fehiepsi!
