### ISSUE TITLE
Update PyTorch builds and run all tests

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1088]
- [x] There have been more changes to v0.4.0 PyTorch branch. Update CI wheels and test on mac.
 - [ ] Run cuda tests using the latest changes in the release branch.

**Comment by fritzo** [comment]
Should we simply point to the PyTorch wheels now?

**Comment by neerajprad** [comment]
> Should we simply point to the PyTorch wheels now?

We should just do that. If and when we need to track again, we can point back to the install scripts.

**Comment by fritzo** [comment]
@neerajprad can you confirm you ran cuda tests so we can close this?

**Comment by neerajprad** [comment]
Just one test to go for python 3.5.
