### ISSUE TITLE
Pyro examples link to incorrect version.

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1097]
Pyro examples link http://pyro.ai/examples/ to pytorch-0.3-279-gdafa1ddd while it should be pyro 0.2

In addtion, the format of second paragraph of bo tutorial is not quite right http://pyro.ai/examples/bo.html.

**Comment by neerajprad** [comment]
I think @jpchen is fixing 1, but not sure what is up with the format there.

**Comment by fehiepsi** [comment]
Ah, the render should be
+ Use the acquisition function to derive the next query point according to ..
+ Evaluate $f(x_{n+1})$ and update the posterior.

But it turns out to be
... + Use the acquisition function to derive the next query point according to ...
`+ Evaluate $f(x_{n+1})$ and update the posterior.`

**Comment by jpchen** [comment]
thanks for pointing it out! just fixed it (you might need to clear your cache)
