### ISSUE TITLE
Support dynamic learning rate

### ISSUE THREAD

**Issue by slaweku** [uber/pyro#1113]
Hi,
Pytorch appear to have a capable module for change learning rates while training: 
https://pytorch.org/docs/stable/optim.html?highlight=scheduler#how-to-adjust-learning-rate
But it embraces the optimizer and when I try to do e.g.
scheduler = MultiStepLR(optim, milestones=[5,10], gamma=0.1)
I am getting
TypeError: PyroOptim is not an Optimizer

So, I was trying to use something like this:

LR_dict={5:1e-3, 10:3e-4}
def adjust_learning_rate(optimizer, epoch, lr_dict):
    if epoch in lr_dict.keys():
        new_lr=lr_dict[epoch]
        print("changing learning rate to:",new_lr)
        for param_group in optimizer.param_groups:
            param_group['lr'] = new_lr

but unfortunately 
AttributeError: 'PyroOptim' object has no attribute 'param_groups'

Regards,
Slawek

**Comment by martinjankowiak** [comment]
thanks, i've been meaning to do this. supporting this will take a little bit of extra engineering in pyro. not very much though so we can try to make the necessary changes within a day or two

**Comment by slaweku** [comment]
Thank you!

**Comment by martinjankowiak** [comment]
you can already do this:

```
from pyro.optim import Adam

def per_param_callable(module_name, param_name):
    if param_name == 'my_special_parameter':
        return {"lr": 0.010}
    else:
        return {"lr": 0.001}

optimizer = Adam(per_param_callable)
```
this should give you the control you want although it doesn't actually use the pytorch 'group' construct

**Comment by slaweku** [comment]
Lovely. Thank you!
