### ISSUE TITLE
Setup fails on Windows

### ISSUE THREAD

**Issue by slaweks17** [uber/pyro#1151]
Hi,
I have been trying to install Pyro 0.2 on Windows 10. After installing latest Anaconda 5.1, I installed Pytorch successfully, although the last command
pip install torchvision
failed with message
PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566)
As I do not care about images, I ignored it.

Unfortunately the same error happen during the subsequent installation of Pyro.
The discussion on https://github.com/pytorch/pytorch/issues/566 did not help me - it is Linux-centric.
I am using Python 3.6.

Any idea how to deal with it?

Thanks,
Slawek

**Comment by fritzo** [comment]
Hi Slawek,
Can you make sure your `pip` is `pip3`, or try
```py
pip3 install torchvision
```
It looks like PyTorch does not provide pip packages for Python 2.7 on windows.

**Comment by slaweks17** [comment]
Hi Fritz,
I am using Python 3.6. I understand that pip will call pip3, anyway, I did try with pip3 and the result is the same. And yes, torchvision is the problem:
pip3 install torchvision
failed during my install of Pytorch. Then, it appears, Pyro is doing it again.

**Comment by fritzo** [comment]
I guess you could try to install Pyro without dependencies
```
pip install --no-deps pyro-ppl
```

**Comment by slaweks17** [comment]
Hi,
Thank you! It appears that it has worked.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
