### ISSUE TITLE
composable guides/autoguides

### ISSUE THREAD

**Issue by karalets** [uber/pyro#1168]
Hey team,

I was looking at the autoguides a bit and have the following request.

It would be cool to be able to define guides over some parts of the model (imagine I have custom inference strategies for particular components int he model) and let autoguides take care of the rest.

This would correspond to composing guides to explain a model and would require some mechanism that would test which variables are taken care of explicitly in the custom guide and which other ones need to be automagically guided.

Currently it feels as if there is some component missing to do this, as we are not attaching scopes to autoguides, but I may also have missed some discussions of course.

One might also consider having two different autoguides scoped over different parts of the model (i.e. a neural autoguide for local variables and an advi autoguide over globals), although I have not thought this particular case through and it may have issues with building proper inverse models and conditioning on previous samples and so on.

Any thoughts on this?

With Regards,

Theo

**Comment by eb8680** [comment]
Interesting idea!  I believe you can already do a simple version of this with `autoguide.AutoGuideList`:
```python
guide = AutoGuideList(model)
guide.add(AutoDiagonalNormal(poutine.block(model, expose=[...])))
guide.add(custom_guide)  # assume custom_guide does not overlap with the AutoDiagonalNormal
...
svi = SVI(model, guide, optim, loss)
for batch in data:
    svi.step(batch)
```

You can also alternate updates for each guide with `poutine.condition`:
```python
guide1 = AutoDiagonalNormal(poutine.block(model, expose=[...]))
guide2 = custom_guide
optim1 = pyro.optim.Adam(...)
optim2 = pyro.optim.Adam(...)
while True:
    guide1_tr = poutine.trace(guide1).get_trace(...)
    SVI(poutine.condition(model, data=guide1_tr), guide2, optim2, loss).step(...)
    guide2_tr = poutine.trace(guide2).get_trace(...)
    SVI(poutine.condition(model, data=guide2_tr), guide1, optim1, loss).step(...)
````

**Comment by karalets** [comment]
Thanks Eli, this looks really nice and idiomatic with poutine magic.
I am really a fan of solution 1, as it seems like a very natural way to define composable guides in the sense I had in mind. Would be great to have that functionality.

Solution 2 also seems ok, but I prefer the elegance of 1, I do not necessarily want to force the alternating updates, but it is good to see how to do it as this may be useful in different contexts.

**Comment by eb8680** [comment]
You can also write solution 1 directly:
```python
guide_list = [AutoDiagonalNormal(poutine.block(model, ...)), custom_guide]
composite_guide = lambda *args: tuple(guide(*args) for guide in guide_list)

svi = SVI(model, composite_guide, optim, loss)

svi.step(...)
```
