### ISSUE TITLE
[Bug?] HMC and NUTS are too sensitive to step-size for simplle Gamma/Beta model

### ISSUE THREAD

**Issue by arranger1044** [uber/pyro#1174]
### Issue Description

 A very simple generative model---a Beta likelihood whose two parameters have a Gamma prior on them:

$$\alpha\sim Gamma(1, 1)$$
$$\beta\sim Gamma(1, 1)$$
$$x\sim Beta(\alpha, \beta)$$

and then running `NUTS` to perform MCMC inference on it, leads to
the acceptance probability to be 0 poor and hence garbage estimates for $\alpha$ and $\beta$.

Changing the stepsize in `HMC`fixes the issue, but `NUTS` should be more robust to this scenario.

Plus, without enabling debugging log messages, the fact that 0 uncorrelated samples were actually provided was totally hidden. I guess I should open a new issue for a feature request for better output?

This issue has been referenced also in this forum post https://forum.pyro.ai/t/simple-mcmc-on-gamma-beta-providing-wrong-estimates/259

### Environment
 - Ubuntu `17.04`, python `3.6`
 - PyTorch `0.4.0`
 - Pyro `0.2.1`

### Code Snippet
```
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as ss
import torch
from torch.autograd import Variable
import pyro
import pyro.distributions as dist
import pyro.infer.mcmc as mcmc
from pyro.infer.abstract_infer import EmpiricalMarginal


a = 5
b = 1
n_samples = 1000
beta_data = ss.beta(a=a, b=b).rvs(n_samples).astype(np.float32)
print(beta_data.shape)
plt.hist(beta_data, bins=100)
plt.show()

def beta_model(data):
    alpha_0 = torch.ones(1)
    beta_0 = torch.ones(1)
    alpha_prior = pyro.sample('alpha', dist.Gamma(concentration=alpha_0, rate=beta_0))
    beta_prior = pyro.sample('beta', dist.Gamma(concentration=alpha_0, rate=beta_0))
    x = pyro.sample('x', dist.Beta(concentration1=alpha_prior, concentration0=beta_prior), obs=data)
    return x

# hmc_kernel = mcmc.HMC(beta_model, step_size=0.0855, num_steps=4)
nuts_kernel = mcmc.NUTS(beta_model, adapt_step_size=True)
mcmc_run = mcmc.MCMC(nuts_kernel, num_samples=1000, warmup_steps=10000).run(torch.from_numpy(beta_data))
beta_posterior = EmpiricalMarginal(mcmc_run, 'beta')
print('beta', beta_posterior.mean) 
alpha_posterior = EmpiricalMarginal(mcmc_run, 'alpha')
print('alpha', alpha_posterior.mean)
```

**Comment by neerajprad** [comment]
> Plus, without enabling debugging log messages, the fact that 0 uncorrelated samples were actually provided was totally hidden.

Yes, I think we should have a better default handler, as this is crucial for debugging how HMC/NUTS is doing. Yes, please create an issue for this, and I'll take care of that!

**Comment by arranger1044** [comment]
Thanks a lot @neerajprad
