### ISSUE TITLE
Make poutine.broadcast as fast as hand parallelization

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1180]
Currently, `poutine.broadcast` will be slower than hand-parallelizing the same example using `.expand_by`. This is because `poutine.broadcast` uses `.expand` which constructs new distribution instances under the hood, whereas `.expand_by` reuses distribution instances. 

Example:
```python
In [10]: import torch
In [11]: prof_expand = lambda d: d.expand((1000, 1000, 10)).log_prob(torch.ones(1000, 1000, 10))
In [11]: prof_expand_by = lambda d: d.expand_by((1000, 1000, 10)).log_prob(torch.ones(1000, 1000, 10))

In [26]: %timeit prof_expand(dist.Normal(0., 1.))
226 ms ± 4.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [27]: %timeit prof_expand_by(dist.Normal(0., 1.))
121 ms ± 1.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

This is understandable as constructing distribution instances isn't cheap. For many small models, this difference might not be perceptible, but with lots of sample sites and iaranges, the difference could add up for more complicated models. 

With more usage of `poutine.broadcast`, it will be good to start thinking about how we can make `.expand` more performant. A couple of options are:
 - defer to `.expand_by` whenever possible.
 - implement `.expand` in `torch.distributions` in a way that reuses those instances or at least bypasses some of the expensive steps in `__init__` (I haven't thought through this fully, and it might not be possible).

**Comment by fritzo** [comment]
It sounds reasonable to defer to `.expand_by()` whenever possible, since this is not very intrusive.

**Comment by neerajprad** [comment]
Deferring to `.expand_by` mostly fixes the issue, but I discovered that there is another source of slowness in the `Dice` class when the `num_particles` dimension is anything but the rightmost:

```python
class Dice(object):
    ...
    def in_context(self, shape, ordinal):
        ...
        # TODO replace this naive sum-product computation with message passing.
        log_prob = sum(self._get_log_factors(ordinal))
```

This arises due to summing a tensor with a large batch dimension (due to num particles for instance) that is not the right-most dimension.

```python
In [13]: %timeit sum([np.random.randn(2, 1000000, 1, 1), np.random.randn(2, 1, 1000000, 2, 1)])
258 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [14]: %timeit sum([np.random.randn(2, 1, 1, 1000000), torch.randn(2, 1, 1, 2, 1000000)])
131 ms ± 4.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

While the difference seems great, the actual impact is fairly low. e.g. the `test_enum.py::test_elbo_iarange_iarange` (set of 81 total tests) on my local mac notebook:

 - Without any fixes - 46 seconds.
 - Deferring to .expand - 35 seconds.
 - Using iarange as rightmost - 30 seconds.

I don't suppose there is an easy fix for this. I will change the priority of this issue once the `.expand` -> `.expand_by` PR is merged.

**Comment by neerajprad** [comment]
Bumping the priority lower now that #1187 is merged.

**Comment by eb8680** [comment]
@neerajprad what's the status of this in PyTorch 1.0?

**Comment by neerajprad** [comment]
This can be closed now since we have already implemented `.expand` methods directly for each of the distributions. There are still a few optimizations we can make there. e.g. https://github.com/pytorch/pytorch/issues/11389 but that's a micro-optimization on the pytorch side.
