### ISSUE TITLE
Issue with signing up for the forum with github

### ISSUE THREAD

**Issue by paddyhoran** [uber/pyro#1200]
This is likely not the right place for this question, I wasn't sure where else to ask it...

I want to sign into the forum with my github account.  I thought I had done this some time ago but I have constant problems with signing in.

I have signed up for many other similar forums and I have not had any issues signing in with my github account.  I have since revoked access in github for the forum in an attempt to start over but I am still facing issues.

Could someone please remove any knowledge of me from the forums backend so I can attempt to set it up again?

**Comment by jpchen** [comment]
unless you give me your email i cant do that. however from a quick search you dont seem to be in the system. what is the error you see?

**Comment by paddyhoran** [comment]
Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

**Comment by paddyhoran** [comment]
I approved everything that was sent, checked junk for further e-mails, etc.

**Comment by jpchen** [comment]
it says that youre authenticated via your github account with the email you specified. i deactivate your account and resent the validation email. if that does not work i can delete your account entirely, let me know what you'd like me to do

**Comment by paddyhoran** [comment]
I also use my iPhone to check discourse forums and it feels flaky...  @jpchen thanks for the help I'll try it out later and report back

**Comment by paddyhoran** [comment]
I'm using Firefox, the link works and provide an "Click here to activate your account"  button but the next screen says "Sorry, this account confirmation link is no longer valid. Perhaps your account is already active?". 

@jpchen can you please delete my account completely when you get a chance and I'll try again, thanks.

**Comment by jpchen** [comment]
hm your account seems to no longer in the system, i cant  query your username or email. i recommend creating a brand new account. sorry for the inconvenience, discourse has a lot of issues

**Comment by paddyhoran** [comment]
ok, I've taken enough of your time away from **real** work :), thanks for trying
