### ISSUE TITLE
Updating tutorials for Pyro 0.2.1

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1208]
I just realized that our tutorial for [tensor shapes](http://pyro.ai/examples/tensor_shapes.html) has not been updated to reflect the changes corresponding to [Pyro 0.2.1](https://github.com/uber/pyro/releases/tag/0.2.1), i.e. the section on `poutine.broadcast` is missing, and it seems that we are pointing to `0.2.0` instead. 

@jpchen - could you take a look?

**Comment by jpchen** [comment]
this is already merged into dev correct? ill rebuild it tonight

**Comment by neerajprad** [comment]
> this is already merged into dev correct? 

Thanks, @jpchen. Yes, this should be in dev.

**Comment by jpchen** [comment]
done
