### ISSUE TITLE
SVI failed with vectorize_particles=True in pytorch master

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1221]
With the BernoulliBetaTests, `test_elbo_reparameterized` failed if we use `vectorize_particles=True` (`num_particles=2`). It passed when we set `vectorize_particles=False`.

**Comment by fehiepsi** [comment]
Interesting, I cannot pass that test. The error is 0.0 vs 1.2. Maybe I am using Pytorch master. Let me check again.

**Comment by neerajprad** [comment]
Its odd that it’s failing on PyTorch master though. Will take a look.

**Comment by fehiepsi** [comment]
So I change the title and reopen it again. :)

**Comment by fehiepsi** [comment]
@neerajprad This is a pytorch bug, not a Pyro bug, so I'll close this. I raised the issue here: https://github.com/pytorch/pytorch/issues/9521.

**Comment by neerajprad** [comment]
Thanks for digging in, and creating the issue, @fehiepsi.
