### ISSUE TITLE
Renyi ELBO does not work with Rejector

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1222]
In Rejector, both `entropy_term` and `score_function_term` are non-zero. I don't know how to derive the formula for Renyi elbo in that case, so I leave the issue here.

I think that it is the main reason why RenyiELBO failed for ShapeAugmentedGamma in `test_inference::test_exponential_gamma`.

**Comment by fritzo** [comment]
You could raise a `NotImplementedError` in that case.

**Comment by fehiepsi** [comment]
Close because this is just a minor issue.
