### ISSUE TITLE
there is no basic MCMC tutorial and example 

### ISSUE THREAD

**Issue by bionicles** [uber/pyro#1223]
given "basics before brilliance," how do you justify omission of a basic mcmc tutorial+example for pyro?

**Comment by eb8680** [comment]
Please see the [eight schools](https://github.com/uber/pyro/blob/dev/examples/eight_schools/mcmc.py) or [baseball](https://github.com/uber/pyro/blob/dev/examples/baseball.py) examples for basic introductions to MCMC in Pyro.  If you find these examples insufficient, feel free to ask questions on our forum or open another issue or pull request with improvements.

**Comment by eb8680** [comment]
Closing this in favor of #979
