### ISSUE TITLE
Unable to register into the Pyro forum

### ISSUE THREAD

**Issue by easysoft2k15** [uber/pyro#1280]
I tried many time to register into the pyro forum:
[https://forum.pyro.ai]
The site keep telling me that I'll receive a confirmation email but I never got one.
I request the email many time, I tried to change email address, I check spam message but nothing worked.
I'v also tried to register with github but I get an error:

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

Doing it from a cookie clean browser make it ask for a password but it then return a similar error.
Can somebody please help?
Thank You

**Comment by neerajprad** [comment]
Not sure if this is a recent issue, but another on the [forum](https://forum.pyro.ai/t/svi-for-classification/324) mentioned about github authentication not working.

**Comment by easysoft2k15** [comment]
This morning i retry the "Resend email" link and it worked!
Not sure if this was a bug or a temporary problem.
In any case I guess You can now close the issue.
Thank You

**Comment by eb8680** [comment]
Discourse can be a little finicky sometimes, especially with SSO.  Closing as resolved.
