### ISSUE TITLE
Move .enumerate(expand=False) logic upstream

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1336]
We've [patched](https://github.com/uber/pyro/blob/dev/pyro/distributions/torch.py) PyTorch distributions to allow a new kwarg `.enumerate_support(expand=False)`, used by enumeration. The interface is now stable and used in a few Pyro inference algorithms. It would be good to push these changes upstream to PyTorch before the next PyTorch release.

**Comment by fritzo** [comment]
@neerajprad do you think you'd have time to address this in the next couple weeks?

**Comment by neerajprad** [comment]
Sure! I will make this change in PyTorch upstream.

**Comment by neerajprad** [comment]
Addressed in https://github.com/pytorch/pytorch/pull/11231. Corresponding Pyro code being removed in https://github.com/uber/pyro/pull/1377.
