### ISSUE TITLE
[discussion] Posterior sampling post Bayesian regressions

### ISSUE THREAD

**Issue by sadatnfs** [uber/pyro#1341]
Hello,

I have been able to run all of the Bayesian regression example on the docs (http://pyro.ai/examples/bayesian_regression.html) with some tweaks for better understanding (like adding multiple weights/features), but I have no idea how I'd go about sampling from the posterior distributions of the weights and the biases. 

Any thoughts or help?

Thanks!

Nafis

**Comment by fritzo** [comment]
Hi @sadatnfs, you should be able to simply run the guide to sample from the posterior
```py
lifted_module = guide(data)
```
If you want more detailed information from the guide, you can modify its return statement.

**Comment by jpchen** [comment]
look at the [tutorial](http://pyro.ai/examples/bayesian_regression.html#Validating-Results) for an example of this. also in the future, please post questions related to usage/examples on the [forum](http://forum.pyro.ai) and use issues for bug reports

**Comment by sadatnfs** [comment]
Oh I didn't know there was a forum! Thanks!
