### ISSUE TITLE
HMM tests crashing on CUDA

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1379]
Many of our HMM tests are crashing on CUDA. I think it could be a GPU memory issue, but it is hard to say because the process crashes with `Fatal Python error: Aborted` without any stack trace. 

Example test that crashes:

```
CUDA_TEST=1 PYRO_TENSOR_TYPE=torch.cuda.DoubleTensor pytest -v tests/infer/test_enum.py::test_elbo_hmm_in_model[parallel-30-False]
```

cc. @fritzo

**Comment by fritzo** [comment]
PyTorch cuda tensors only support 25 dimensions IIRC, so we'll only be able to run HMMs with at most ~28 dims. Let's just `xfail if cuda` the params that require long chains.

**Comment by neerajprad** [comment]
Sounds good; I'll skip these tests on CUDA for now.

**Comment by neerajprad** [comment]
Closing this - lets track the issue in #1380.
