### ISSUE TITLE
Problem with a definition of the HalfCauchy distribution

### ISSUE THREAD

**Issue by dimarkov** [uber/pyro#1389]
### Issue Description
After making a fresh installation of pyro in python 3.7 using
`pip install pyro-ppl`
in an anaconda environment I suddenly receive an error when 
defining a HalfCauchy distribution, e.g. 
`pyro.distribution.HalfCauchy(torch.zeros(10), torch.ones(10))`

returns the following error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/markovic/data/miniconda/envs/pyro/lib/python3.7/site-packages/torch/distributions/half_cauchy.py", line 32, in __init__
    validate_args=validate_args)
  File "/media/markovic/data/miniconda/envs/pyro/lib/python3.7/site-packages/torch/distributions/transformed_distribution.py", line 56, in __init__
    super(TransformedDistribution, self).__init__(batch_shape, event_shape, validate_args=validate_args)
  File "/media/markovic/data/miniconda/envs/pyro/lib/python3.7/site-packages/torch/distributions/distribution.py", line 29, in __init__
    if self._validate_args:
RuntimeError: bool value of Tensor with more than one value is ambiguous
`

The problem seems to be related to a change in the way one should define a 
HalfCauchy distribution, as the following works 
`pyro.distribution.HalfCauchy(torch.ones(10))`

So it is not really a bug, but more a misleading documentation which has the following description 
of HalfCauchy distribution
`class HalfCauchy(loc, scale)`

digging a bit trough the source code showed that the HalfCauchy is now part 
of pytorch distributions and they use a different initialization compared to how it 
was defined in pyro before. 

### Environment
For any bugs, please provide the following:
 - OS: linux mint and python version 3.7.0.
 - PyTorch version: 0.4.1.post2.
 - Pyro version: 0.2.1

**Comment by fritzo** [comment]
Don't use PyTorch 0.4.1 release, it's too buggy. Instead use PyTorch 0.4.0 or wait until the next release.

PyTorch 0.4.0 does not have a `HalfCauchy`, so Pyro provides its own.

**Comment by neerajprad** [comment]
Just a heads up (as you already observed) - the `torch.distributions` implementation of HalfCauchy in master assumes that `loc` is fixed at `0`, whereas the Pyro implementation provides a `loc` parameter that can be used for translation. In the next release, we will be moving to use the torch implementation, so the `HalfCauchy` will not take in a `loc` parameter. You can still wrap it in a `TransformedDistribution` if you need to translate it.
