### ISSUE TITLE
Clean up _Subsample, _subsample

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1393]
PyTorch is much easier to use than it was when we first wrote `_Subsample` and friends. Let's
- [x] Replace `torch.randperm(...)[:...]` -> `torch.multinomial(replacement=False)`
- [x] Replace `use_cuda` kwarg -> `device`, which is more idiomatic and supports multi-gpu.
- [x] Replace `torch.LongTensor(list(range(...))).cuda()` -> `torch.arange(..., device=device)`
- [x] Replace `torch.zeros(1)` -> `torch.tensor(0., device=device)`

See also #1392

**Comment by neerajprad** [comment]
Should be addressed in #1392. I initially was targeting `dev`, but our `torch-0.4.0` is quite far behind when it comes to scalar support, and I was having to write work-arounds and removing them in our `pytorch-0.5.0` branch.
