### ISSUE TITLE
distributions should have a field entropy (H) of distribution

### ISSUE THREAD

**Issue by karalets** [uber/pyro#141]
Also referenced within #91 .
When we get some time we should start adding those.

This will be helpful for analytical KL divergences.
@neerajprad suggests also adding the cross-entropies, I think this is up to discussion, since there is a combinatorial number of those.

**Comment by martinjankowiak** [comment]
@fritzo can we close this in favor of distributions conversations happening elsewhere?

**Comment by neerajprad** [comment]
@fritzo created a related task in [probtorch#36](https://github.com/probtorch/pytorch/issues/36). Closing this issue.
