### ISSUE TITLE
Significant slowdown in HMC on PyTorch master

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1421]
Some of the HMC tests in `pytorch-0.5.0` are taking much longer (~1.8-2 X) longer, e.g. `test_gamma_normal_with_dual_averaging`. The cprofile results show that most of the slowdown is in the distribution's `log_prob` methods.

**Comment by fehiepsi** [comment]
@neerajprad Do you have a good new? I thought `log_prob` for of small models is still more expensive than before?

**Comment by fehiepsi** [comment]
Ah, I just saw your announcement in pytorch. +1
