### ISSUE TITLE
test_mixture_of_diag_normals gives wrong loss on linux

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1425]
The following tests fail on linux, because the `hand_loss` (~85) is very different from the `auto_loss` (~20). I am only observing this issue with PyTorch master on linux, and not Mac OSX.

```
tests/infer/test_enum.py::test_mixture_of_diag_normals[MixtureOfDiagNormals-scale0] 
tests/infer/test_enum.py::test_mixture_of_diag_normals[MixtureOfDiagNormalsSharedCovariance-scale1]
```

**Comment by neerajprad** [comment]
cc. @martinjankowiak

**Comment by neerajprad** [comment]
This is related to https://github.com/pytorch/pytorch/issues/12230.

**Comment by fritzo** [comment]
We're only using `torch.masked_fill_()` in three places in Pyro. I think it's reasonable to work around this via a helper
```py
def torch_masked_fill(destin, mask, value):
    destin.masked_fill_(mask.contiguous(), value)
```

**Comment by neerajprad** [comment]
Since we only require the destination tensor to be contiguous, there was only a single place in the code where we needed to make a change (in `pytorch-0.5.0`). Closing this issue, we can directly track the upstream issue instead.
