### ISSUE TITLE
MCMC results fail to pickle

### ISSUE THREAD

**Issue by ColCarroll** [uber/pyro#1426]
### Issue Description
The results of `MCMC` inference fail to pickle.  

### Environment
For any bugs, please provide the following:
 - I am on ubuntu, python 3.6.6
 - `torch==0.4.1`
 - `pyro-ppl==0.2.1`

### Code Snippet
I have mostly copied the eight schools example from the pyro examples. Running the [code available here](https://gist.github.com/ColCarroll/ebbe5f59299b97dd447b5472cc0d8672), and then trying to save throws an exception. `dill` and `cloudpickle` throw longer, but similar exceptions.

```python
data = {
        'J': 8,
        'y': np.array([28., 8., -3., 7., -1., 1., 18., 12.]),
        'sigma': np.array([15., 10., 16., 11., 9., 11., 10., 18.]),
    }
posterior = pyro_centered_schools(data, 500, 500)

with open('test.pkl', 'wb') as buff:
    pickle.dump(posterior, buff)
```
```pythontb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-1d7554473cc5> in <module>()
      1 with open('test.pkl', 'wb') as buff:
----> 2     pickle.dump(posterior, buff)

TypeError: can't pickle weakref objects
```

**Comment by neerajprad** [comment]
One problem with directly pickling the `MCMC` or `TracePosterior` (parent) classes is that they contain reference to `sample` methods for generating traces. I think the correct level at which we should pickle is the `EmpiricalMarginal` class, which is simply of holder of samples, and should be straightforward to pickle. 

e.g.
```python
    posterior = MCMC(nuts_kernel, num_samples=args.num_samples, warmup_steps=args.warmup_steps)\
        .run(model, data.sigma, data.y)
    marginal_mu_tau = EmpiricalMarginal(posterior, sites=["mu", "tau"])\
        .get_samples_and_weights()[0].squeeze().numpy()
    with open('test.pkl', 'wb') as buff:
        pickle.dump(marginal_mu_tau, buff)
```

Would this work? One issue is that it will only contain the latent sites that the user specified in the call to `EmpiricalMarginal` and not all sites. e.g. it may not have the observation nodes by default. It is possible to store all the latent and observation samples by default and then return the subset that is requested by the users, but it will require some change internally.

**Comment by ColCarroll** [comment]
Thank you for the suggestion! My goal is to test pyro compatibility in arviz, and the api currently accepts the `MCMC` object directly, then uses `EmpiricalMarginal` internally to extract the data. In fact,
```
arviz.convert_to_inference_data(posterior).to_netcdf('test.nc')
``` 
is a good way of storing the data, doing pretty much what you said, we just need to figure out how to unit test that!

With pymc3/pystan/emcee, the test suite will train a model and then cache that, so that CI and local development is not too slow. I am going to follow your suggestion, and try removing the references to the functions in our test suite and see if that fixes things.

**Comment by ColCarroll** [comment]
Well, this works at least for now:

```python
for trace in posterior.exec_traces:
    for node in trace.nodes.values():
        node.pop('fn', None)
posterior.kernel = None
posterior.run = None
posterior.logger = None
```
