### ISSUE TITLE
[FR] Add tutorial on implementing new effects

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1451]
Users at PROBPROG 2018 requested a tutorial on high-level Pyro architecture including advanced features like poutines.  This issue proposes adding a tutorial on implementing a new effect handler.

Whereas #1553 should aim to explain Pyro's architecture in a simplified way, this tutorial should prepare developers to make changes to Pyro.

**Comment by robsalomone** [comment]
Hi guys, has there been any progress with this issue? Would been keen to see any current drafts of tutorials and provide feedback. This sort of tutorial really is necessary I think to get the scientific community on board to implement new methodology they are working on (or in general, to encourage and make contributions easier).

**Comment by eb8680** [comment]
@robsalomone sorry, I've been busy with other things and haven't had time to get to this.  It'll definitely be included with the [0.3.0 release](https://github.com/uber/pyro/milestone/5), which will hopefully be out in a few weeks.  I agree it's important for encouraging contributors and I'll cc you when I open a PR with a draft.

**Comment by eb8680** [comment]
@robsalomone have a look at [minipyro.py](https://github.com/uber/pyro/blob/dev/pyro/contrib/minipyro.py) and #1629
