### ISSUE TITLE
[FR] Add tutorial on automatic guides

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#1452]
Users at PROBPROG 2018 noted that it can be tedious to write guides. A tutorial on autoguides might help this.

**Comment by jpchen** [comment]
ive pointed two users to the gmm tutorial for an autoguide example. what example models would be helpful? maybe a hierarchical logistic regression like stan's advi has?

**Comment by karalets** [comment]
I think I have asked Eli this before. Could one build automatic sub-guides?
I. E. Each time a name is instantiated?
Currently MVN guides will put everything together, which is oftentimes too
much.

**Comment by fritzo** [comment]
@karalets Yes you can build automatic sub-guides using [AutoGuideList](http://docs.pyro.ai/en/0.2.1-release/contrib.autoguide.html#autoguidelist). Let me know if you can share a motivating example that I can showcase in our tutorial.

**Comment by karalets** [comment]
My bad, let me study it and get back to you!

**Comment by karalets** [comment]
Ah, that seems to be the thing I discussed with Eli back then. Glad to see
it is a feature in the meantime that I shamefully missed.

**Comment by fritzo** [comment]
> do ... autoguides work well enough ...?

We have two types of autoguides:
1. Boring old non-data-dependent autoguides like `AutoDelta` (for MAP), `AutoDiagnoalNormal` for mean-field SVI, `AutoMultivariateNormal` and `AutoLowRankMultivariateNormal` for correlated SVI, and `AutoGuideList` to combine the above (e.g. to express block diagonal correlation structure in a `AutoMultivariateNormal`, or to MAP-estimate some variables and use a custom guide for others via `AutoGuideList`). These have been tested on a wide class of models and seem to work well (e.g. in my forecasting work).
2. Fancy data-dependent autoguides, of which our only example is `AutoIAFNormal`. This is the cool research direction that could eventually incorporate architecture search, program induction, etc. To my knowledge these have not been tested on a wide class of models.

Given that we use `AutoDelta`+`AutoGuideList` in many examples, I thought it would be worth starting a tutorial describing the non-data-dependent guides. As our research progresses, we could add a second part or second tutorial on data-dependent autoguides.

**Comment by fritzo** [comment]
Closing for now, since this was mostly addressed in #1623 and #1630 . Thanks @jpchen!
