### ISSUE TITLE
Make dynamic distribution mixin wrappers in torch.py picklable

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1456]
We load torch distributions and create distribution mixin classes dynamically in `torch.py`. These distribution instances are not picklable however.

```python
>>> pickle.dumps(Pareto(1., 1.))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'pyro.distributions.torch._PyroDist'>: it's not the same object as pyro.distributions.torch._PyroDist
```
We may need to provide more help to `pickle` to be able pickle / unpickle these instances. Note that this is not currently an issue with most distribution classes since they have a small wrapper in Pyro (containing `.expand` method), but will be in `pyro==0.3` where we are constructing these wrappers automatically.

### Why do we need this?

This will be useful in the multiprocessing context where workers send back traces to the main process. All elements in the trace (inc. distribution instances) should be picklable in that case. An alternative design would be to not send back the full trace, but only the empirical distribution itself, but this is worth exploring only if the overhead of trace serialization/deserialization is considerable.

**Comment by fritzo** [comment]
I'd guess we can simply set `type(...).__name__` to e.g. `Pareto` and set that as a module level variable in the `pyro.distributions.torch` module.

**Comment by neerajprad** [comment]
@fritzo - This is only an issue if we have distribution classes in PyTorch that we would like to dynamically import. 

If `Pareto` is available as a module level variable in `pyro.distributions.torch`, then pickle wouldn't have an issue. Declaring all distribution classes in the `torch` module upfront  is definitely one solution (and maybe better than being too clever). But I might have misunderstood your solution - would it work with dynamic importing?
