### ISSUE TITLE
Improvements for Tensor Shape Tutorial

### ISSUE THREAD

**Issue by martinjankowiak** [uber/pyro#1475]
Various todos:

- [ ] Be more explicit about _conditional_ independence where appropriate
- [ ] others?

**Comment by jpchen** [comment]
probably should do this after all the renaming/new semantics is complete eg #1406

**Comment by eb8680** [comment]
Maybe we should consider adding some logging functionality that automatically generates model shape visualizations like the ones in the tutorial?
