### ISSUE TITLE
Update Bayesian Regression tutorial

### ISSUE THREAD

**Issue by jpchen** [uber/pyro#1480]
A few possible revisions for 0.3 :
- [x] replace BR example
- [x] rewrite current bayesian reg to use autoguides
- [x] convert #1282 to manual guides and into a tutorial

**Comment by eb8680** [comment]
Suggested in #1282: One possibility is to replace the autoguides in #1282 with manual ones and make that the main Bayesian regression tutorial, then turn the current Bayesian regression tutorial into a rehash of that one that demonstrates the use of autoguides and `random_module`/`lift`.

**Comment by jpchen** [comment]
will discuss this offline next week before implementing. was also thinking of separating the HMC part out of #1282 and creating a separate HMC tutorial (with the same data) and including the visualized comparisons with SVI.
