### ISSUE TITLE
Refactoring MCMC module

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1520]
We have added a lot of important features to HMC while addressing #1093. This has come at the expense of class complexity, particularly for HMC and MCMC classes. It will be great to refactor some of this code to make it amenable to extend, understand and debug.
 - [x] Remove `use_experimental_einsum` flag and make `TraceEinsumEvaluator` the default in HMC/NUTS.
 - [x] Refactoring the adaptation code to be separate from the HMC class. This currently toggles a lot of mutable attributes that makes debugging difficult. 
 - [x] Making it easy for the user to specify an initial trace to begin sampling from (based on @fehiepsi's suggestion in #1511).
 - [ ] Own implementation of progress bar that is specialized to our use case than having to work around tqdm's (which is a great general purpose progress bar otherwise) quirks. - Low Priority
 - [x] Make progress bar consistent when number of decimals of step_size change. - Low Priority
 - [x] Blocked call with timeout when reading from the shared queue in ParallelSampler.
 - [x] Refactoring the TracePosterior / ParallelSampler classes to support chain level diagnostics.
 - [ ] Refactoring to support parallel chains on CUDA - we will need to hold the traces temporarily within each worker until its read by the main process. Ref. to discussions [#1](https://discuss.pytorch.org/t/invalid-device-pointer-using-multiprocessing-with-cuda/28023/6), [#2](https://discuss.pytorch.org/t/cuda-tensors-on-multiprocessing-queue/28626/2)
 - [ ] Any other?

**Comment by neerajprad** [comment]
Removing from the milestone - the only major task left is to support parallel chaining with CUDA.

**Comment by fehiepsi** [comment]
I think we can merge this and https://github.com/uber/pyro/issues/1093. In issue 1093, it seems that there is only one remaining issue: "Detect divergent transitions, and log them for analysis. Throwing a NaN here during sampling as we might do now with validation check enabled, is not very useful to the end user."
