### ISSUE TITLE
Change interface of EmpiricalMarginal to support diagnostics

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#1560]
Refer to the discussion in https://github.com/uber/pyro/pull/1557, #1545. 

We now have diagnostics like effective sample size, gelman rubin that we would like to make available for MCMC. Based on @fehiepsi's suggestion and my experience with #1557, it seems that the best way to do this would be to:

 - Modify the `EmpiricalDistribution` to aggregate across both chain and sample dimensions. This way any user should be able to access the samples per chain corresponding to a latent site. Currently, samples from all chains are merged in together, and chain information is not available. 
 - Change the interface of `EmpiricalMarginal` so that it does not inherit from `EmpiricalDistribution`  (breaking change, but I think it will be for the better) and can take in latents having different sizes (currently it isn't possible to do so in `EmpiricalDistribution` because of the inconvenience associated with having ragged tensors). Corresponding to each latent site, we'll create an empirical distribution. Each latent can be accessed as `marginal.site("a")`. 
 - Regarding diagnostics, these can reside inside of `EmpiricalMarginal`. e.g. `marginal.effective_sample_size()` which will give the ESS for all the latents as a dict, or it can reside in `EmpiricalDistribution` (@fehiepsi's suggestion). I would prefer the former so as to keep the usage of `EmpiricalDistribution` completely internal.

@eb8680, @fehiepsi - What do you think?

**Comment by neerajprad** [comment]
Another issue is that this is also used by importance sampling for which these diagnostics might not make sense. 

So another design choice could be to have separate `EmpiricalMarginal` implementations for importance and MCMC, which can be accessed via `trace_posterior.empirical(sites=["a", "b"])`. That way we can also move the ESS computation for importance into its own marginal implementation.

**Comment by eb8680** [comment]
Sounds great, I'm all for modernizing `EmpiricalMarginal`.  I also agree it should probably be an MCMC-specific thing, along with `TracePosterior`/`TracePredictive`.  We can figure out `Importance` separately.

**Comment by fehiepsi** [comment]
@neerajprad Your changes in #1557 are pretty clean to me! I'll comment there some nits which I catched.
