### ISSUE TITLE
module 'pyro' has no attribute 'plate'

### ISSUE THREAD

**Issue by dongfeng951** [uber/pyro#1563]
When I run lda.py in the example directory, there is an error.

Traceback (most recent call last):
    File "lda.py", line 137, in <module>
        main(args)
    File "lda.py", line 105, in main
        true_topic_weights, true_topic_words, data = model(args=args)
    File "lda.py", line 35, in model
        with pyro.plate("topics", args.num_topics):
AttributeError: module 'pyro' has no attribute 'plate'

What is the problem?
Thanks.

**Comment by fehiepsi** [comment]
I think you need to use Pyro dev: `pip install git+https://github.com/uber/pyro`.

**Comment by jpchen** [comment]
all examples need to be run with the `dev` version of pyro

**Comment by dongfeng951** [comment]
Thanks! I will try it.

**Comment by beckybai** [comment]
Does pyro 0.3 needs pytorch 1.0?

**Comment by neerajprad** [comment]
> Does pyro 0.3 need pytorch 1.0? 

That's right. We are waiting for pytorch 1.0 release before releasing pyro 0.3, but you should be able to use the pytorch pre-release version with pyro 0.3.
