### ISSUE TITLE
paper about lda.py

### ISSUE THREAD

**Issue by dongfeng951** [uber/pyro#1565]
Hi, I read the code of lda.py and I find it introduces NN for inferring the document topics. This is an interesting idea and I am curious about the paper which describes it.  Does anyone know the paper?
Thank you!

**Comment by eb8680** [comment]
I don't know the topic model literature well enough to say whether there's a paper about that specific model and inference setup, but similar ideas have appeared pretty frequently in the last few years, e.g. the [Neural Variational Document Model](http://proceedings.mlr.press/v48/miao16.pdf) or [Neural Statistician](https://arxiv.org/abs/1606.02185).

Also, for future reference, please ask questions about models on the [forum](http://forum.pyro.ai/) - we try to keep GitHub issues to feature requests, bug reports, and other development-related discussion.

**Comment by dongfeng951** [comment]
Hi, Thank your very much!

**Comment by eb8680** [comment]
Happy to help!
