### ISSUE TITLE
 'dmm.polyphonic_data_loader' has no attribute 'load_data'

### ISSUE THREAD

**Issue by dongfeng951** [uber/pyro#1566]
When I run hmm.py example, there is an error. 
AttributeError: module 'dmm.polyphonic_data_loader' has no attribute 'load_data'
Then I check the polyphonic_data_loader.py, and I cannot find load_data(). Is there anything missing?
Thank you!

**Comment by neerajprad** [comment]
Please use the `dev` branch of Pyro to run the `hmm` example. You should be able to see `load_data` in `poloyphonic_data_loader` on the dev branch. Note that this will be part of the next release in a few weeks.

**Comment by jpchen** [comment]
i like (3). i was actually thinking of adding a README to examples as a short-term remedy, since most people discover them through the github webpage.

**Comment by dongfeng951** [comment]
Hi, Thank you very much!

**Comment by neerajprad** [comment]
I think (3) is best (i.e. each example has an associated minimum version), since examples might build on functionality that require the `dev` branch and it might not be feasible to port those changes to master always.
