### ISSUE TITLE
Error "Cannot install a messenger instance twice"

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1567]
I am trying to use `autoname` module but keep getting the error in the title.

```
import torch.nn as nn
from pyro.contrib import autoname

class A(nn.Module):
    @autoname.name_count
    def __call__(self, *args, **kwargs):
        return super(A, self).__call__(*args, **kwargs)

class B(A):
    def forward(self, x):
        return x

class C(A):
    def __init__(self, b):
        super(C, self).__init__()
        self.b = b
    
    def forward(self, x):
        return x + self.b(x)

b = B()
c = C(b)
c(1)  # error
```
I am not sure how to solve this problem. There is a note about raising this error in the [messenger.py](https://github.com/uber/pyro/blob/dev/pyro/poutine/messenger.py#L61) file and the following script does not raise any error
```
@autoname.name_count
def c(x):
    @autoname.name_count
    def b(x):
        return x
    return x + b(x)

c(1)  # no error
```
I appreciate any help!

**Comment by eb8680** [comment]
Your two scenarios are not equivalent.  This error is caused by the way decorators work: the decorator is called once at class definition, not each time a new instance is created.  A version of the second scenario that should raise the same error as the first is:
```python
nc = autoname.name_count()

@nc
def c(x):
    @nc
    def b(x):
        return x
    return x + b(x)

c(1)  # error
```

The safest way to get around this is to use `name_count` as a context manager:
```python
class A(nn.Module):
    def __call__(self, *args, **kwargs):
        with autoname.name_count():
            return super(A, self).__call__(*args, **kwargs)
```

**Comment by fehiepsi** [comment]
Thank you so much @eb8680 ! Your solution works like a charm.
