### ISSUE TITLE
Specifying parameters to update during inference

### ISSUE THREAD

**Issue by dustinvtran** [uber/pyro#158]
`KL_QP`-like algorithms currently have the args `model_fixed=False` and `guide_fixed=False` to control whether their parameters are fixed during inference (`KL_QP.step()`). This is restrictive for compositional inferences where you might establish two `KL_QP` algorithms, each of which handles parameter updates of a different latent variable.

It would be nice if the arg is more locally at the parameter level, where the user might pass in a list of trainable variables. One question is how to handle the dynamic case when the list of trainable variables grows at runtime so the user can't specify the list a priori. `model_fixed` and `guide_fixed` do handle this case, so maybe a hybrid of these two approaches?

I ran into this issue when playing with probabilistic PCA in https://github.com/uber/pyro/issues/112 and following Edward's approach of 5 local updates per 1 global update.

**Comment by ngoodman** [comment]
what's the status of this proposal? seemed like everyone was on board... plan for 0.2?

**Comment by fritzo** [comment]
This should be easier to implement if we switch from `.backward()` to `torch.autograd.grad()` #628 , which in turn should be easier once PyTorch optimizers support `torch.autograd.grad()` https://github.com/pytorch/pytorch/issues/4179 .

**Comment by eb8680** [comment]
I believe #1060 resolves the original issue, and we can discuss scoping elsewhere
