### ISSUE TITLE
GMM tutorial broken in current dev build

### ISSUE THREAD

**Issue by kgero** [uber/pyro#1584]
### Environment
Mac OS, Python 3.6.1. Originally installed pyro with pip. 

torch=0.4.1 pyro=0.2.1

### Issue 
I was having the same issues as areshytko (see on the forum [here](https://forum.pyro.ai/t/gmm-example-in-documentation-gives-warning-about-from-traceenum-elbo/394/5)) when trying to run the GMM tutorial (http://pyro.ai/examples/gmm.html). 

```
UserWarning: TraceEnum_ELBO found no sample sites configured for enumeration. If you want to enumerate sites, you need to @config_enumerate or set infer={"enumerate": "sequential"} or infer={"enumerate": "parallel"}? If you do not want to enumerate, consider using Trace_ELBO instead.
warnings.warn('TraceEnum_ELBO found no sample sites configured for enumeration. '
```

While it would run, the results were bad -- no clear convergence, and couldn't correctly find the two clusters (put everything into one cluster).

Since it seems like it was fixed recently, I installed pyro from the dev branch. However, then the code would not run at all. (Apologies for not including the actual error; I tried to revert but then it was an issue with using torch==0.4.1 and not torch==0.4.0 (couldn't find `logsumexp`) and I couldn't figure out exactly.

I fixed this issue by reverting to commit `4c89c99e1026a4d87e53b2f2e813b41b78f6a439` (which a friend of mine was on, and she had successfully run the tutorial). Also seems like commit `43155bf967921f9ddccd2998d97186f0c2ff2f7a` works fine (for the tutorial) but the next one doesn't (with the update to pytorch==1.0.0).

**Comment by neerajprad** [comment]
The `dev` branch in Pyro is currently tracking the PyTorch pre-release to prepare us for a release next week. I think the example should run if you were to install pytorch [pre-release](https://pytorch.org/), but let me know if you face any issues.

**Comment by neerajprad** [comment]
My recommendation would be to use the `pytorch-0.4.0` branch (which has all recent changes) which is compatible with pytorch version 0.4.0, for another week or so until release, so that you don't have to deal with constant flux on both PyTorch and Pyro as they prepare for release!

**Comment by neerajprad** [comment]
Closing this, please feel free to reopen if you continue to see issues.
