### ISSUE TITLE
JIT for differentiable_loss

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#1594]
Currently, we have `jit` version of `loss_and_grads`. It would be nice to have that version for `differentiable_loss` too. I expect that it would be similar?

**Comment by eb8680** [comment]
Just use `pyro.ops.jit.trace`: 
```python
loss = TraceEnum_ELBO(...).differentiable_loss
jit_loss = pyro.ops.jit.trace(functools.partial(elbo, model, guide))
```

**Comment by eb8680** [comment]
Note that `pyro.ops.jit.trace` is just a thin wrapper around `torch.jit.trace` that makes sure `pyro.param` statements are visible, so you might even be able to just use `torch.jit.trace` if you're getting your parameters from a `nn.Module` and not ever interacting with the parameter store.
