### ISSUE TITLE
the sum of doc_topics is not equal 1

### ISSUE THREAD

**Issue by dongfeng951** [uber/pyro#1681]
Hi, I have a question. when I run lda.py, I find the sum of `doc_topics` is not equal 1. In fact, they are decreasing in the training process. 
I check the code, I find `doc_topics` is just output of sigmoid functions, so there is no mechanism to guarantee the sum is 1. 
But I think in the LDA model, the sum should be one.
Is there something wrong?
Thanks

**Comment by eb8680** [comment]
This constraint is enforced by [`distributions.Categorical`](https://pytorch.org/docs/stable/distributions.html#categorical), which normalizes its inputs.

In the future, please ask questions on the [forum](https://forum.pyro.ai/).

**Comment by dongfeng951** [comment]
Thank you. So I have to add  `distributions.Categorical` to the outputs to make the sum equal one?

I will ask questions on that forum.

**Comment by eb8680** [comment]
> So I have to add distributions.Categorical to the outputs to make the sum equal one?

In the LDA example, the topic probabilities you were concerned about are passed into `Categorical`, where they are normalized automatically.  If you want to work with them directly, you can just normalize them yourself by summing and dividing by the sum: `probs = probs / probs.sum(-1, keepdim=True)`

**Comment by dongfeng951** [comment]
> > So I have to add distributions.Categorical to the outputs to make the sum equal one?
> 
> In the LDA example, the topic probabilities you were concerned about are passed into `Categorical`, where they are normalized automatically. If you want to work with them directly, you can just normalize them yourself by summing and dividing by the sum: `probs = probs / probs.sum(-1, keepdim=True)`

But I find the sum of `doc_topics` not equal one. Therefore, I raise this question.

**Comment by eb8680** [comment]
> But I find the sum of doc_topics not equal one. Therefore, I raise this question.

The `doc_topics` value in the guide is passed into a `Categorical` in the model by `SVI` during training, so inference works as expected.  If you want to work with `doc_topics` from the guide directly, you'll need to normalize them yourself, as I said.

**Comment by dongfeng951** [comment]
Thanks. I understand it.
