### ISSUE TITLE
make test: no attribute 'optim' error in 'examples/contrib/oed/ab_test.py' 

### ISSUE THREAD

**Issue by ciaobladoo** [uber/pyro#1684]
### Issue Description
On the latest dev branch, `make test` gives the following error:

_
examples/contrib/oed/ab_test.py:12: in <module>
    from gp_bayes_opt import GPBayesOptimizer
examples/contrib/oed/gp_bayes_opt.py:11: in <module>
    class GPBayesOptimizer(pyro.optim.multi.MultiOptimizer):
E   AttributeError: module 'pyro' has no attribute 'optim'

### Environment
For any bugs, please provide the following:
 - OS and python version: CentOS Linux 7 (Core); Python 3.7.1
 - PyTorch version, or if relevant, output of `pip freeze`: PyTorch 1.0.0
 - Pyro version: output of `python -c 'import pyro; print pyro.__version__'`: pyro 0.3.0+9adbdb7

### Code Snippet

```
make install
make format
make test
```

**Comment by fritzo** [comment]
That's weird, my guess is that `make` isn't picking the right conda env / virtual env or something, so that `make test` picks up an outdated pyro version. Can you try to repeatedly
```sh
pip uninstall pyro-ppl
```
You can test locally more quickly using
```sh
pytest -v tests/test_examples.py -k ab
```
