### ISSUE TITLE
Clear pyro._param_store on error

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#175]
It would make it much easier to debug models and guides if we cleared the global `_param_store()` on error. E.g. I've been trying to get types to match in a `model` and `guide`, and errors don't surface until I run `inference.step()`. But on failure, some stale param values remain.

I suggest we wrap all inference methods in something like

```py
try:
    ...do inference...
finally:
    pyro.get_param_store().clear()
```

**Comment by martinjankowiak** [comment]
let's close this for now because i don't think we have any demand for the kinds of enhancements/solutions proposed here
