### ISSUE TITLE
Pyro docker image

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#195]
As discussed in #114, it will be nice to have a dockerfile that we can use to build a docker container with pyro and all its dependencies packaged in, specially for running on a GPU. I suppose this will need to wait until we make Pyro public (as pip / git clone will not work with restricted access), but opening this task to keep track of the issue.

**Comment by eb8680** [comment]
@neerajprad let's try to have this ready after the new PyTorch release

**Comment by neerajprad** [comment]
Yes, that's next on my task list.
