### ISSUE TITLE
Use PyTorch/Google style in Distributions docstrings

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#196]
To ease future migration of `pyro.distributions` to `pytorch`, we should adopt their [docstring style](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md):

> PyTorch uses [Google style](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for formatting docstrings. Length of line inside docstrings block must be limited to 80 characters to fit into Jupyter documentation popups.

In particular, this implies
- [ ] 80 character line length in docstrings. (This is important for Jupyter usability!)
- [ ] Single line description, followed by paragraphs of longer text, followed by `Args`, `Returns`
- [ ] `Args:`, `Returns:`, and `Raises:` instead of `:param:`, `:return:`, and `:raises:`

**Comment by martinjankowiak** [comment]
@fritzo is this now moot given that we already went with a particular docstring format?

**Comment by eb8680** [comment]
@martinjankowiak @fritzo is this change being made upstream?

**Comment by neerajprad** [comment]
I suppose this was to ease migration of the distribution library to PyTorch. Since PyTorch already follows this format, and we are rewriting all the distributions directly there, I think we can close this task.

@fritzo - Feel free to reopen, if you think there is something we need to track within Pyro.

**Comment by fritzo** [comment]
This is fine to close. We're basically moving the math from pyro.distributions to torch.distributions and adopting the torch docstring conventions there.
