### ISSUE TITLE
Utility for using python class methods as functions

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#255]
All our distribution class can be instantiated with the parameter values, e.g. `x = dist.Bernoulli(ps=a)` after which we can call various methods without having to specify the distribution parameters `x.sample()`, `x.log_pdf(data=X)`. These can also be used as functions instead in which case they are called with all the distribution parameters, like `dist.bernoulli.sample(ps=a)`. In all of these distribution classes, we have `_sanitize_input` method which defaults to the parameter values specified at object creation time if those are not passed in to the methods during call. The sanitize method does some basic checks, but it does not always check that all the parameter values not specified during a method call are valid instance parameters, or that both are not simultaneously specified. It becomes very clunky to do this for all distributions.

We can create a separate decorator method `default_class_params` as a utility that provides a way to use class methods as functions. It inspects that any missing parameter values are present as instance parameters and does some basic assertions. e.g. to check that they are not being simultaneously specified. If assertions pass, it calls the functions with the correct defaults, else raises an exception. This will remove `_sanitize_input` method calls from distribution classes, and ensure that all the error checking can happen in one place.

**Comment by fritzo** [comment]
Closed by #334 implementing the `RandomPrimitive`
