### ISSUE TITLE
guide construction with poutine magic

### ISSUE THREAD

**Issue by ngoodman** [uber/pyro#263]
The problem: it can be a drag to write simple guides for VI, often requiring duplicated code from the model. What's more, it's easy to get the names wrong so guide and model don't line up. We certainly want to have available the option of providing a guide in complete detail, but it would be nice to have more compact ways to make standard guides.

The proposal: taking a queue from `poutine.lift`, which shifts the type of a param site to sample while also inserting additional computation, we should be able to make `poutine.parametrize` that intercepts the parameters to the distribution at a sample site, inserting a computation to get them (which might include new param sites).

I imagine this would look something like:

~~~py
def model():
    x = pyro.sample("foo", dist, params)
    ...

def foo_params(dist, old_params):
    guide_dist = dist  #explicitly provide dist, in case we want to guide with a different dist
    guide_args = pyro.param("foo_params", ...)  #the trainable params, dist args computed from them
    return guide_dist, guide_args

guide = pyro.parameterize(model, {"foo": foo_params})

Optimize(model, guide,...)
~~~

much as in lift, in addition to the simple map from names to param fns, we could instead provide a function from name and site info (dist etc) that computes params. it should be straightforward to use this to make an auto-mean field guide: `guide = pyro.parameterize(model, make_mean_field)`.

using parameterize to provide amortized guides may require some extension. i'm not sure the correct interface in general, but simply providing the args of the model to the params function is a start:

~~~py
def model(data):
    x = pyro.sample("foo", dist, params)
    ...
    pyro.observe(dist, data)

def foo_params(dist, old_params, fn_args):
    guide_dist = dist 
    amortized = pyro.module("bar", ...)
    guide_args = amortized(fn_args)  #fn_args will be bound to the arguments of the model/guide 
    return guide_dist, guide_args

guide = pyro.parameterize(model, {"foo": foo_params})
~~~

is there a more general version? does this need to change to play nicely with irange/iarange?

note: the parameterize poutine yields a style similar to the WebPPL method of providing guides in-line in the model. i think doing this as operations on a model fn is more composable though.

**Comment by fritzo** [comment]
This has roughly been implemented in the `pyro.contrib.autoguide` module.
