### ISSUE TITLE
Compatibility with PyTorch distributions

### ISSUE THREAD

**Issue by eb8680** [uber/pyro#306]
Apparently PyTorch is adding a distributions library: see [docs](http://pytorch.org/docs/master/distributions.html), [PR](https://github.com/pytorch/pytorch/pull/3165),  [issue](https://github.com/pytorch/pytorch/issues/3185).  We should try to coordinate with them to make sure we're compatible and to avoid duplicating work...

**Comment by fritzo** [comment]
Closing this in favor of more targeted issues. @fritzo and @neerajprad on the Pyro team are working with @colesbury, @apaszke, @jwvdm, and @dustinvtran to converge a distributions interface and contribute code upstream.
