### ISSUE TITLE
Add alpha-divergence minimization

### ISSUE THREAD

**Issue by jpchen** [uber/pyro#35]
A more general form of KL-divergence could be useful. 
https://arxiv.org/pdf/1511.03243.pdf

Allows you to do things like [estimation for GANs](https://arxiv.org/pdf/1610.02920.pdf) where the generator minimizes the f-divergence and the discriminator does a density ratio estimation.

**Comment by fehiepsi** [comment]
@jpchen I guess this is handled in #1214 (not so sure because the formula of this paper's alpha divergence is different to Renyi's one), so I close this. Please open again if you think that they are different.
