### ISSUE TITLE
Further profiling -- small tensor models

### ISSUE THREAD

**Issue by ngoodman** [uber/pyro#361]
@hawkrobe noticed that VI in pyro is *much* slower than in webppl for a simple hierarchical regression example. this is not totally unexpected since this model has only very small tensors (and uses irange instead of vectorized iarange for data). we expect pyro to be faster when computation time is dominated by tensor computation (forward+backward).

it would still be useful to do some profiling for models like this: i suspect there is a bunch of unnecessary overhead that we don't notice for more tensor-heavy tests (like vae), and which might be easy to correct.

**Comment by eb8680** [comment]
@neerajprad @fritzo was this issue mostly addressed by the overhead reductions in PyTorch 0.3?

**Comment by jpchen** [comment]
theres been noticeable improvements with 0.3 with the models robert and i are running. not amazing, but better. i imagine the rest is due to the interpreter.
