### ISSUE TITLE
Auto-format python code

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#394]
This issue proposes setting up code formatters for python code.

## Why?

**Readability:** Autoformatted code improves readability in collaborative projects (at least of code *other people* write :wink:).

**Accepting Contributions:** When outside contributors submit PRs, we can focus review comments on the important semantic changes and delegate trivial style decisions to an autoformatter.

**Refactoring:** Autoformatting makes codebase-wide refactoring easier. Specifically during minor rename refactorings, autoformatters can fix lint errors due to changed indentation and maximum line length limits.

## How?

We'll configure a few industry-standard formatters to match our existing coding style (e.g. 120char line limits):
- [Yapf](https://github.com/google/yapf) is a mature formatter for general python code. Plugins are available for Sublime, Vim, etc.
- [Isort](https://pypi.python.org/pypi/isort) is a mature formatter that focuses on import order and is a little more configurable than `yapf` for this purpose. Plugins are available for Sublime, Vim, etc. (this addresses #393 )

These will be easy to run via a `make format` command, or inside your editor/IDE.

Since autoformatting will cause painful merge conflicts for any unmerged branches, we'll ensure that all outstanding branches are merged before merging any REFORMAT THE WORLD pull requests. We'll break this into stages:
- [x] #408 Run `isort` on `tests/` and `pyro/` (should not cause merge conflicts)
- [ ] Run `isort` on `examples/`
- [x] #430 Run `yapf` on `pyro/distribtions/`
- [ ] Run `yapf` on `pyro/`
- [ ] Run `yapf` on `tests/`
- [ ] Run `yapf` on `examples/`

**Comment by eb8680** [comment]
@fritzo is this still going to happen?

**Comment by fritzo** [comment]
I'd rather focus engineering effort elsewhere.
