### ISSUE TITLE
Abstract Trace_kernel class from which MCMC kernels will inherit.

### ISSUE THREAD

**Issue by ngoodman** [uber/pyro#44]
Kernels take a trace and return a trace.

**Comment by fritzo** [comment]
Am I correct that kernels must take a (model, trace) pair and return a trace? I believe a model is needed because kernels will need to run model code to correctly set up gradients among `Variable`s in the trace.

**Comment by ngoodman** [comment]
yes, the kernel is model specific. but rather than having the kernel take the model each time, i think we might want the kernel constructor to take the model, and the kernel to just take the trace.

**Comment by eb8680** [comment]
First version implemented in #579 by @neerajprad
