### ISSUE TITLE
Add scripts for microbenchmarking and profiling

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#460]
We should have some scripts to run microbenchmarks of `pyro.distributions` and larger benchmarks of `pyro.infer.SVI`. In the past I've set up scripts to run ~1minute long profiles and spit out a summary of (less than one terminal screen of) information, so that it's easy to A/B test a change on a local machine (travis machines are too variable for benchmarking). Profiling scripts should take arguments for:
- which component to profile
- the size of data (tiny tensors or large tensors)
- cpu or cuda
- how long to run (10sec-1minute is ideal)
- which profiler to use (`/usr/bin/time`, snakeviz, valgrind, `line_profiler`, etc.)

It's also nice if profiling tools are part of the main package, so that users can time operations on their own machine with e.g.
```sh
$ python -m pyro.distributions.profile
$ python -m pyro.infer.profile
```

Here are some profiling scripts I've used in the past:
https://github.com/posterior/treecat/blob/master/treecat/profile.py
https://github.com/posterior/loom/blob/master/loom/benchmark.py
https://github.com/fritzo/pomagma/blob/master/src/make.py#L142

**Comment by fritzo** [comment]
@neerajprad Can we close this now that you've added profiling scripts?

**Comment by neerajprad** [comment]
Yes, profiling will always be an ongoing issue. Will create new issues as needed.
