### ISSUE TITLE
mailing list and/or live-chat channel

### ISSUE THREAD

**Issue by dustinvtran** [uber/pyro#496]
Are these available yet? Or is there a plan for when they'll be released?

**Comment by eb8680** [comment]
We're working on setting up gitter

**Comment by jpchen** [comment]
we'll also set up a discourse so people can openly ask questions and see other people's answers

**Comment by stepelu** [comment]
What would be an expected timeline for the above?

I have some questions / feedback about Pyro and I'm a bit reluctant to abuse of the issue tracker for this

**Comment by fritzo** [comment]
Hi @stepelu We'll have something by EOD today.

**Comment by fritzo** [comment]
Ok we now have http://forum.pyro.ai
