### ISSUE TITLE
Naming issue?

### ISSUE THREAD

**Issue by MikeTam1021** [uber/pyro#512]
You do understand that python already has a Pyro package that has been around for a long time? Who did the research on the decision to market this package as ‘Pyro’? From what I see it doesn’t even make much sense... Pyro is for ‘python remote objects’ what does it mean here?

**Comment by fritzo** [comment]
Thanks for pointing this out Mike. We saw that the Pyro remote objects library had been renamed to [Pyro4](https://pypi.python.org/pypi/Pyro4), and that the original [Pyro](https://pypi.python.org/pypi/Pyro) hasn't been maintained for over 5 years. While we agree with the original Pyro team's policy of keeping the unmaintained Pyro on pypi, we thought that the 5+ year gap was a safe point to recycle the name.

**Comment by MikeTam1021** [comment]
It is the same name space in terms of idioms. My team already works with Pyro4 as a tool and commonly refer to it as "pyro". It is a naming conflict in terms of idioms, which is what programming is about. 

I know it seems very witty/creative, whatever, to name something Pyro (Python, Torch, fire, pyrotechnics, I get it) but why not just keep it simple and go with uber-ppl or something that will never face a naming conflict. That will have more utility to more python users.
