### ISSUE TITLE
causal inference tutorial

### ISSUE THREAD

**Issue by tbenst** [uber/pyro#517]
Currently, [this page](http://pyro.ai/examples/intro_part_ii.html#Parametrized-Stochastic-Functions-and-Variational-Inference) links to a [causal inference tutorial](http://pyro.ai/examples/causal_inference.html), which does not exist.

**Comment by eb8680** [comment]
Yeah, good catch, that didn't make it into 0.1.0. I'll remove the reference.

**Comment by jpchen** [comment]
that link has been removed and will be reinstated when the causal tutorial is written. feel free to track its progress in #455
