### ISSUE TITLE
Links to source code of the API docs are broken

### ISSUE THREAD

**Issue by datapythonista** [uber/pyro#532]
For example, in the documentation of the `sample` method of the `Bernoulli`distribution class:

http://docs.pyro.ai/primitive_dist.html#pyro.distributions.bernoulli.Bernoulli.sample

The `[source]` link is set to:

http://docs.pyro.ai/_modules/pyro/distributions/bernoulli.html#Bernoulli.sample

But it should be instead:

https://github.com/uber/pyro/blob/dev/pyro/distributions/bernoulli.py#L72-L76

This happens with all the API documentation for what I could see.

**Comment by neerajprad** [comment]
@jpchen - Could you take a look? It seems like we may be missing the `_modules` folder, as I can see the links are pointing correctly locally.

**Comment by neerajprad** [comment]
@jpchen - Could you take a look? It seems like we may be missing the `_modules` folder, as I can see the links are pointing correctly locally.

**Comment by jpchen** [comment]
@datapythonista thanks for pointing this out! it's been fixed and deployed. feel free to reopen if you continue seeing a problem

**Comment by datapythonista** [comment]
It's fixed now, thanks for taking care of it so quickly!
