### ISSUE TITLE
Should running a conditioned model forward throw an error?

### ISSUE THREAD

**Issue by stuhlmueller** [uber/pyro#535]
In Pyro, this runs without throwing an exception:

```py
def model():
    return pyro.sample("x", dist.normal, Variable(torch.ones(1)), Variable(torch.ones(1)))

conditioned_model = pyro.condition(model, data={"x": Variable(torch.Tensor([2]))})

print(conditioned_model())
```

By contrast, running the equivalent model in WebPPL throws an error ("factor allowed only inside inference.") Should Pyro throw an error as well?

**Comment by eb8680** [comment]
Ah, good catch.  I think the ideal behavior would be a warning rather than an error or silence, since it can be useful for debugging to run constrained models forward.  This is currently what happens if `pyro.observe` is used in a model with no enclosing `Poutine`.
