### ISSUE TITLE
Documentation for `iarange`

### ISSUE THREAD

**Issue by srush** [uber/pyro#542]
http://docs.pyro.ai/primitives.html#pyro.__init__.iarange

I had trouble understanding this documentation. Seems to be written for a maintainer as it refers to several things that are not in the docs: context manager, traces, etc.

**Comment by eb8680** [comment]
Thanks for pointing this out, this is definitely too obtuse for a user-facing construct.  We should fix the docstring and possibly write a tutorial about subsampling as requested by #67 .

**Comment by martinjankowiak** [comment]
it may be worth pointing out that all of this is discussed in the second svi tutorial. (at least from a user's perspective). which isn't to say the discussion couldn't be improved.

**Comment by srush** [comment]
Yeah, tutorial is helpful, but ideally the docs shouldn't require it.
