### ISSUE TITLE
infer.Marginal not documented 

### ISSUE THREAD

**Issue by srush** [uber/pyro#543]
Seems like an important function but not documented except by example.

**Comment by fritzo** [comment]
@eb8680 @neerajprad Is the `Marginal` interface to add to sphinx docs in our 0.2 release? The docstring could use a bit more detail and an `Example usage::` section.

**Comment by eb8680** [comment]
`Marginal` is being removed by #1019 which adds `EmpiricalMarginal`, which should be covered in an HMC tutorial.  We can add an example from one of the sampling tests to its docstring as well.

**Comment by neerajprad** [comment]
@fritzo -  Thanks for the heads up. I'll handle that in the pending PR.

**Comment by fritzo** [comment]
`EmpiricalMarginal` is now documented [here](http://docs.pyro.ai/en/0.2.1-release/inference_algos.html#pyro.infer.abstract_infer.EmpiricalMarginal) and appears in multiple examples.
