### ISSUE TITLE
SVI (and others) should provide a direct reference to parameters

### ISSUE THREAD

**Issue by srush** [uber/pyro#544]
The only way to access the parameters after SVI is through the global store. Since SVI knows which parameters it is currently optimizing, would be nice you could call `svi.params()` to see them.

**Comment by martinjankowiak** [comment]
but which parameters? the parameters from the most recent gradient step? every time the mode/guide pair is called will in general result in a different set of parameters.

**Comment by srush** [comment]
How about everything it has touched so far?

**Comment by eb8680** [comment]
Addressed by #1060
