### ISSUE TITLE
multiple versions of documentation, one per release (+dev)

### ISSUE THREAD

**Issue by dustinvtran** [uber/pyro#547]
Having docs for varying versions, especially dev and master, sounds useful for development. I don't know if Pytorch has a good solution but I like that TF has multiple versions. FWIW, read the docs does this automatically: https://docs.readthedocs.io/en/latest/index.html.

relevant: https://github.com/uber/pyro/pull/545#issuecomment-343333425

**Comment by ngoodman** [comment]
we did this in webppl (using readthedocs) and it worked nicely. (all though it meant i pointed people to the dev docs most of the time ;)

**Comment by jpchen** [comment]
unfortunately you can only do that if it is hosted on readthedocs.org. pytorch does this manually which is why they have this [hacked together page](http://pytorch.org/docs/versions.html). the problem with this is that, our doc files will scale with each release, which will be a lot of overhead when a user clones pyro.

**Comment by neerajprad** [comment]
How about hosting documentation / tutorials on readthedocs, and retaining our domain name - http://docs.readthedocs.io/en/latest/alternate_domains.html?

**Comment by jpchen** [comment]
oo hm this seems new ill look into this

**Comment by jpchen** [comment]
docs.pyro.ai (give 24 hours for CNAME to propagate)

**Comment by neerajprad** [comment]
Great! 
 - Can we opt out of the ads (http://docs.readthedocs.io/en/latest/ethical-advertising.html#opting-out)? They seem kind of pesky.
 - Can we get our old CSS back?

**Comment by jpchen** [comment]
> Can we opt out of the ads

nope - i already opted out of paid ads but thats all we can do on the free tier

>Can we get our old CSS back?

Go for it :)
