### ISSUE TITLE
Add continuous values for data in the Bernoulli test fixtures

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#564]
Ref. #539. 

We should either throw an error if the data to be scored is continuous for the Bernoulli distribution or have some continuous samples for testing if we would like to allow this. 

If we go with the second option (consistency with tensorflow could be a reason), we should have our test fixtures reflect this by having test data in the range `[0, 1]`.

**Comment by martinjankowiak** [comment]
@neerajprad @fritzo can we close this because it's being tracked in distributions issues in probtorch?

**Comment by neerajprad** [comment]
Closing; we can close most distribution issues (except those that track building wrappers/shims on the Pyro side).
