### ISSUE TITLE
Error Occurred while installing using `pip install git+https://github.com/uber/pyro.git`

### ISSUE THREAD

**Issue by shravankumar147** [uber/pyro#565]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-354niw25/torch/

**Comment by jpchen** [comment]
can you paste your command and the output? the description currently isnt very descriptive

**Comment by shravankumar147** [comment]
pip install git+https://github.com/uber/pyro.git
Collecting git+https://github.com/uber/pyro.git
  Cloning https://github.com/uber/pyro.git to /tmp/pip-6c_pysdz-build
Requirement already satisfied: numpy>=1.7 in ./anaconda3/lib/python3.6/site-packages (from pyro-ppl==0.1.2)
Requirement already satisfied: scipy>=0.19.0 in ./anaconda3/lib/python3.6/site-packages (from pyro-ppl==0.1.2)
Collecting cloudpickle>=0.3.1 (from pyro-ppl==0.1.2)
  Downloading cloudpickle-0.5.1-py2.py3-none-any.whl
Collecting graphviz>=0.8 (from pyro-ppl==0.1.2)
  Downloading graphviz-0.8.1-py2.py3-none-any.whl
Collecting networkx>=2.0.0 (from pyro-ppl==0.1.2)
  Downloading networkx-2.0.zip (1.5MB)
    100% |████████████████████████████████| 1.6MB 121kB/s 
Collecting observations>=0.1.4 (from pyro-ppl==0.1.2)
  Downloading observations-0.1.4.tar.gz (483kB)
    100% |████████████████████████████████| 491kB 663kB/s 
Collecting torch (from pyro-ppl==0.1.2)
  Downloading torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-354niw25/torch/setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).
    
    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-354niw25/torch/

**Comment by jpchen** [comment]
Seems like the error is what it says above, 
```
RuntimeError: PyTorch does not currently provide packages for PyPI (see status at pytorch/pytorch#566).
Please follow the instructions at http://pytorch.org/ to install with miniconda instead.
```

how are you installing pytorch?

**Comment by shravankumar147** [comment]
trying to install with this command: 
`pip install git+https://github.com/uber/pyro.git`

**Comment by jpchen** [comment]
please follow the [installation instructions](https://github.com/uber/pyro#installation).

**Comment by jpchen** [comment]
closing this issue as it seems to be a non issue. please reopen if you encounter problems from following the installation instructions. we highly recommend following the instructions for both pytorch and pyro to avoid these types of problems.
