### ISSUE TITLE
Maximum a posteriori inference

### ISSUE THREAD

**Issue by nbren12** [uber/pyro#570]
I am considering using pyro for my problem, but I don't quite grok the library yet.  Part of my confusion comes from SVI being the main well documented inference engine in pyro, and I am a beginner to variational inference.

For me, the simplest "inference" methods to understand are maximum a posteriori (MAP) and maximum likelihood, and it would be nice if the `pyro` had some examples of these. I assume `pyro` has the optimization tools necessary to handle MAP, but the documentation is not very clear about how to do it.

**Comment by eb8680** [comment]
Great question!  You can do MAP inference by using SVI with `Delta` distributions in your guide:
```python
def model():
    mu = pyro.sample("mu", dist.normal, Variable(torch.zeros(1)), Variable(torch.ones(1)))
    return pyro.sample("x", dist.normal, mu, Variable(torch.ones(1)))

def guide():
    mu_param = pyro.param("mu_param", Variable(torch.randn(1), requires_grad=True))
    return pyro.sample("mu", dist.delta, mu_param)
```

For maximum likelihood, you can either put very wide `Uniform` priors on your latent variables in the model and proceed with deltas in the guide as above, or you can change the `sample` statements in your model into `param` statements and use an empty guide:
```python
def model():
    mu = pyro.param("mu", Variable(torch.randn(1), requires_grad=True)))
    return pyro.sample("x", dist.normal, mu, Variable(torch.ones(1)))

def guide():
    return None
```

**Comment by nbren12** [comment]
Thanks so much for that description. I am still a little confused about how variational inference with delta functions as the approximating distribution reduces to MAP.  This is something that `edward` also glosses over in its [MAP documentation](http://edwardlib.org/api/ed/MAP). I guess the ELBO equals the log of joint probability in the case when q(z) is a delta function. Would it be worth adding an inference class for this special case?

**Comment by fritzo** [comment]
:+1: for a helper along the lines of
```py
def MAP(model, *args, **kwargs):
    guide = poutine.lower(model)  # poutine.lower is opposite of poutine.lift
    return SVI(model, guide, loss="ELBO", *args, **kwargs)
```

**Comment by eb8680** [comment]
> I guess the ELBO equals the log of joint probability in the case when q(z) is a delta function

Yep, this is correct.

> Would it be worth adding an inference class for this special case?

We could do something like what @fritzo suggested but I'm partial to the manual `Delta` guide method because it doesn't require executing the model twice.

**Comment by nbren12** [comment]
At least for beginners, I think it would be nice to have a MAP convenience function which someone who knows nothing about variational inference can use.

**Comment by ngoodman** [comment]
Great use case of poutine.lower!

**Comment by fritzo** [comment]
@nbren12 I believe #573 should work for you. The purpose of SVI and guides (over simple MAP) is to be able to deal with latent variables whose value you want to integrate over, rather than optimize. The purpose of the guide is to provide a good random guess for each latent variable.

**Comment by kjchalup** [comment]
@eb8680 
1) In your MAP and MLE examples, where does the data come into play? In particular, you didn't 'observe' anything. If data is not involved, how can pyro learn the values? 
2) Pyro documentation insists that the guide 'samples' the same latents as the model. However,  this is not the case in any of your examples. Is there a bug in the examples?
3) It would be great if you could provide an actual minimal running example -- e.g. learn the mean of an actual dataset of 100 numbers sampled from a Gaussian distribution.

Please help - I'm also trying to learn pyro starting from these basic cases and am finding it very difficult -- which is a shame, there seems to be great potential here!

**Comment by fritzo** [comment]
@kjchalup This should MAP estimate the mean `mu_est` of numbers packed into `data`:
```py
def model(data):
    pyro.sample('mu', normal, Variable(torch.zeros(1)), Variable(torch.ones(1)))
    for i, x in enumerate(data):
        pyro.sample('obs_{}'.format(i), normal, mu, Variable(torch.ones(1)), obs=x)

def guide(data):
    mu_map = pyro.param('mu_map', Variable(torch.randn(1), requires_grad=True))
    pyro.sample('mu', delta, mu_map)
```

**Comment by eb8680** [comment]
@kjchalup are your questions specifically about MAP, or about Pyro more generally?  If it's the latter, I recommend our [examples and tutorials](http://pyro.ai/examples/index.html), especially the [introductory inference tutorial](pyro.ai/examples/intro_part_ii.html) and the [stochastic variational inference (SVI) tutorial](http://pyro.ai/examples/svi_part_i.html).  If the former, here is a more complete version of my snippet above:
```python
def model():
    mu = pyro.sample("mu", dist.normal, Variable(torch.zeros(1)), Variable(torch.ones(1)))
    return pyro.sample("x", dist.normal, mu, Variable(torch.ones(1)))

def guide():
    mu_param = pyro.param("mu_param", Variable(torch.randn(1), requires_grad=True))
    return pyro.sample("mu", dist.delta, mu_param)

# constrain model sample site "x" to be equal to some fixed observed data
conditioned_model = pyro.condition(model, data={"x": data})

svi = pyro.infer.SVI(model=conditioned_model,
                     guide=guide,
                     optim=pyro.optim.SGD({"lr": 0.001}),
                     loss="ELBO")

losses = []
for t in range(1000):
    losses.append(svi.step())

# to get the value of mu, just call guide
mu_final = guide()
```
