### ISSUE TITLE
TransformedDistribution's event_shape forwards to incorrect base distribution's method

### ISSUE THREAD

**Issue by stepelu** [uber/pyro#574]
Probably a typo:

https://github.com/uber/pyro/blob/51a2ccfe9445c7072c3150c4abe1ab1d2ac17246/pyro/distributions/transformed_distribution.py#L62

**Comment by fritzo** [comment]
Could you be more specific? It may be weird that `.batch_shape()` is a method, but that is indeed our current behavior.

**Comment by fritzo** [comment]
Oh sorry, Now I see that `.event_shape()` returns `...batch_shape(...)`. Thanks!
