### ISSUE TITLE
Unable to install pyro

### ISSUE THREAD

**Issue by sriharsha0806** [uber/pyro#578]
I'm using Ubuntu 17.04, I have created conda environment pyro with python 3.5.4 and installed relevant pytorch library. When i'm using pip3 to install pyro i'm getting the following error: 

   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-n3zitztg/pyro/setup.py", line 23
        exec code in constants
                ^
    SyntaxError: Missing parentheses in call to 'exec'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n3zitztg/pyro/
I tried to resolve this issue based on the following https://github.com/facebook/prophet/issues/140 But the error keeps coming.

**Comment by eb8680** [comment]
The name of the package on PyPI is `pyro-ppl`, so you'll need to run `pip3 install pyro-ppl` to install Pyro.  This error seems to be caused by `pip3 install pyro`, which is an unrelated package.

**Comment by sriharsha0806** [comment]
pip3 install pyro-ppl
Collecting pyro-ppl
  Using cached pyro-ppl-0.1.2.tar.gz
Collecting numpy>=1.7 (from pyro-ppl)
  Using cached numpy-1.13.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=0.19.0 (from pyro-ppl)
  Using cached scipy-1.0.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting cloudpickle>=0.3.1 (from pyro-ppl)
  Using cached cloudpickle-0.5.1-py2.py3-none-any.whl
Collecting graphviz>=0.8 (from pyro-ppl)
  Using cached graphviz-0.8.1-py2.py3-none-any.whl
Collecting networkx>=2.0.0 (from pyro-ppl)
  Using cached networkx-2.0.zip
Collecting observations>=0.1.4 (from pyro-ppl)
  Using cached observations-0.1.4.tar.gz
Collecting torch (from pyro-ppl)
  Using cached torch-0.1.2.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nuat_xgu/torch/setup.py", line 11, in <module>
        raise RuntimeError(README)
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).
    
    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nuat_xgu/torch/
I'm still getting the same error; 

Also I tried installing from source but 
git clone git@github.com:uber/pyro.git
Cloning into 'pyro'...
ssh: connect to host github.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I am getting this error

**Comment by jpchen** [comment]
Have you installed pytorch first?

**Comment by eb8680** [comment]
This is a different error - Pyro requires the latest version of PyTorch, but can't use pip to upgrade your installation because PyTorch doesn't provide PyPI packages.  You'll need to install the latest PyTorch release using the instructions from the PyTorch website before you can `pip install pyro-ppl`.

**Comment by sriharsha0806** [comment]
# packages in environment at /home/sriharsha/miniconda3/envs/pyro:
#
pytorch                   0.2.0           py35hb1547bd_4cu80  [cuda80]  soumith

**Comment by sriharsha0806** [comment]
Sorted the installation by running make install @eb8680 @jpchen
