### ISSUE TITLE
Automated checks for tutorial PRs

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#585]
Currently our tests do not capture if there is any regression in the tutorials due to an API change. 
 - It will be nice to be able to run a subset of cells in travis for any PR so as to have some degree of confidence that it does not break our existing tutorials.
 - For tutorial related PRs like #581, we should be able to detect that there are no erroneous statements introduced due to the change.

**Comment by jpchen** [comment]
do our example tests run these tutorials (eg ssvae, air)? that would be starting point to verify existing code isnt broken. most of the tutorial notebooks arent runnable so they would be hard to test directly

**Comment by fritzo** [comment]
`test_examples.py` does test the helper modules in `examples/`, but does not test the notebooks.
```
$ pytest -v tests/test_examples.py -n auto -x

tests/test_examples.py::test_cpu[vae.py]
tests/test_examples.py::test_cpu[air/main.py]
tests/test_examples.py::test_cpu[contrib/named/tree_data.py]
tests/test_examples.py::test_cpu[bayesian_regression.py]
tests/test_examples.py::test_cpu[ss_vae_M2.py]
tests/test_examples.py::test_cpu[dmm/dmm.py]
tests/test_examples.py::test_cpu[vae_comparison.py]
tests/test_examples.py::test_cpu[contrib/named/mixture.py]
tests/test_examples.py::test_cuda[bayesian_regression.py]
tests/test_examples.py::test_cuda[air/main.py]
tests/test_examples.py::test_cuda[dmm/dmm.py]
tests/test_examples.py::test_cuda[vae.py]
```

**Comment by jpchen** [comment]
in that case, we should make sure in review that when an example breaks it has a corresponding fix in the tutorials.

perhaps we can also put a disclaimer at the top of the tutorials on the webpage eg "supported by Pyro vx.x.x/Pytorch vx.x.x", and then the link to the gh code will reference the code compatible with the latest version of pyro

(note this is for all the un-runnable examples, for the other ones we can just run the cells as suggested above)

**Comment by fritzo** [comment]
Already addressed.
