### ISSUE TITLE
Split Categorical into Categorical + OneHotCategorical

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#591]
Blocking #588 

The PyTorch distributions library is planning to follow Tensorflow in separating the two classes `Categorical` (which returns a `LongTensor` of categories) and `OneHotCategorical` (which returns a one-hot `FloatTensor`). Pyro should do the same ASAP.

Note that `Categorical` has also seemed extraordinarily complex to implement and test due to the conflated implementations in the past; this split should help clean up our code and testing. E.g. `OneHotCategorical.analytic_mean()` is well-defined, whereas `Categorical.analytic_mean()` is not.

**Comment by fritzo** [comment]
@neerajprad If you're busy with HMC I'm happy to do this. Just let me know.

**Comment by neerajprad** [comment]
This was fast! :) Taking a look.

**Comment by fritzo** [comment]
> That was fast

This is just a first draft. Tests do not pass.
