### ISSUE TITLE
Add .transform property to constrained distributions for HMC, MAP

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#592]
Blocked by #293 (needs vectorized `TransformedDistribution.log_det_jacobian()`) 

Algorithms like HMC and MAP inference need to be able to automatically update latent variables by some small step. When latent variables are constrained (e.g. drawn from a `Beta`, `Dirichlet`, `Uniform`, or `Exponential`) these algorithms need to be able to transform to an unconstrained parameter space. Must PPL systems do this by registering a `Bijector` or `Bijector` factory that can transform the constrained variable to an unconstrained space.

**Comment by fritzo** [comment]
To avoid duplicating work, we could do this in the `torch.distributions` layer and wait until the wrapping layer matures.

**Comment by fehiepsi** [comment]
It would be a nice feature. Waiting for this!
