### ISSUE TITLE
Include example utils in pip-installed package

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#621]
**Goal:** All examples should be runnable as stand alone python files after `pip install pyro-ppl`.

## Why?

Beginning users often start using Pyro by forking existing examples and modifying them. Currently Pyro's examples include helpers `examples/util.py` and `examples/utils/*`. Since these helpers are not part of the pip-installed package, users are forced to either (1) fork examples in Pyro's `examples/` directory and use Pyro's version control (not ideal for e.g. class projects), or (2) copy all of `pyro/examples/utils/` into their own projects.

## How?

This issue proposes to move helper code (for plotting and data loading) into the main Pyro package. This could be a single package `pyro.contrib.examples` or possibly multiple packages `pyro.contrib.visualization` + `pyro.contrib.datasets`. These new packages would have weaker guarantees for backwards compatibility, so `pyro.contrib` seems like a reasonable home.

**Comment by fritzo** [comment]
@jpchen @neerajprad do you have any opinions on package naming?

**Comment by jpchen** [comment]
this reminds me of a recent forum post with the same problem. not particularly opinionated as to the package namespace, but something like `pyro.examples.data_loader` or `pyro.examples.visualization` makes sense to me. what do you think?

**Comment by neerajprad** [comment]
The names sound fine to me. Longer term, another thing to possibly explore would be separating out the examples as its own package. This will be useful if we have examples that have heavy dependencies like `pandas`, `sklearn` etc. that we don't want the core to inherit. I think PyTorch has a similar approach.

Right now, we are kind of doing that (probably accidentally?) except that everything is being installed from `setup.py`. Both `examples` and `profiler` seem to be top level modules along with `pyro`, and we can do the following import:

```
from examples.utils.custom_mlp import Exp
```
