### ISSUE TITLE
Variance reduction for reparametrized ELBo

### ISSUE THREAD

**Issue by ngoodman** [uber/pyro#63]
For the reparameterizable case (courtesy @eb8680):
- [Reducing reparameterization gradient variance](https://arxiv.org/abs/1705.07880)
- [Reparameterization gradients through acceptance-rejection algorithms](https://arxiv.org/abs/1610.05683)

**Comment by jpchen** [comment]
@martinjankowiak what is the status of this? i dont know if youve looked back at this since your fancy variance-reduced estimators.. otherwise can we close this in favor of concrete tasks?

**Comment by cavaunpeu** [comment]
FWIW, I'm working on a [PR](https://github.com/blei-lab/edward/pull/819/files) for almost this in Edward. Perhaps I can do a port to Pyro when done. Would be 🌴 💯 ☀️ to be back working in PyTorch land...

**Comment by fritzo** [comment]
@cavaunpeu we've implemented RSVI in #659 which should be merged within the next week or two (just needs some clean-up and tests).

**Comment by cavaunpeu** [comment]
Super!

**Comment by fritzo** [comment]
RSVI and Sticking the Landing are already in Pyro. I'm closing this issue in favor of more targeted issues.
