### ISSUE TITLE
Deprecate dependency on scipy for pyro-ppl package

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#633]
Once distributions are migrated upstream and we do not have a core dependency on scipy, we should remove this from our requirements in `setup.py` (add it to test dependencies), so that users do not need to install a separate 16MB file when they do a pip install of `pyro-ppl`.

**Comment by jpchen** [comment]
is this true of numpy as well? (well aside from examples)

**Comment by neerajprad** [comment]
> is this true of numpy as well? (well aside from examples)

I think we use numpy at a few other places, but `numpy` package is really small, a few hundred kbs. It's scipy that we should definitely eliminate once PyTorch distributions library can do the heavy lifting.
