### ISSUE TITLE
Add versioning to tutorials

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#639]
We should version our tutorials to make it easy for our users to refer to the relevant version depending on their version of Pyro install (we can use git tags as labels). As part of #638, we will be making some changes to the `distributions` API that will not be backwards compatible. We will update our tutorials appropriately but this should be as part of the `dev` tag without affecting the tutorials pertaining to the Pyro release tag.

**Comment by jpchen** [comment]
closing in favor of #547
