### ISSUE TITLE
Implement IWELBO

### ISSUE THREAD

**Issue by jpchen** [uber/pyro#671]
Tracking as part of 0.2 or 0.2.1 milestone

**Comment by fehiepsi** [comment]
@jpchen I think that implementing IWELBO (or Renyi ELBO) is quite straightforward but we have to store `num_particles` number of traces to calculate weights. Is this the main obstruction for not having IWELBO at current stage?

**Comment by neerajprad** [comment]
@fehiepsi: `num_particles` is vectorized now, so I think it should be relatively straightforward to implement fast IWELBO for static models at least. @jpchen - what do you think?

**Comment by fehiepsi** [comment]
@neerajprad Nice to hear that! Will try to make a pull request if there is no duplicated work on this. :)

**Comment by jpchen** [comment]
yes - it shouldnt be complex to implement, i just havent gotten the time to doing it. @fehiepsi feel free to implement it if you're already working on it

**Comment by neerajprad** [comment]
Implemented in #1214.
