### ISSUE TITLE
MultivariateNormal.batch_log_pdf() has incorrect gradient

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#685]
It appears that gradient wrt the `scale_tril` argument is incorrect.

The only way I've been able to conclusively diagnose this is by checking the continuity equation on samples, [as is done in PyTorch](https://github.com/pytorch/pytorch/blob/8c2d35c/test/test_distributions.py#L1176). We should probably have continuity equation checks as part of the tests. I've also hand-implemented a `BivariateNormal` in the `mvn-sym` branch; this should have correct gradients and be usable for testing as a reference implementation.

This also shows up in poorly-fit distributions in SVI. Sorry I do not have a reproducible test case.

**Comment by 1Reinier** [comment]
What is the extent of the error here? Still usable or shall I hold off using it in my models? Btw if I can contribute in any way I'd be happy to.

**Comment by fritzo** [comment]
`grad([MultivariateNormal(loc, scale_tril=scale_tril)], [scale_tril])` is incorrect and unusable. We will be dropping `scale_tril` support from `MultivariateNormal` this week as we refactor to use PyTorch distributions in Pyro. Useful parts of Pyro's MultivariateNormal distribution will be moved upstream. If you'd like to help, I suggest contributing to the PyTorch implementation in progress at https://github.com/probtorch/pytorch/pull/52

**Comment by 1Reinier** [comment]
Thanks

**Comment by fritzo** [comment]
Closing in favor of https://github.com/pytorch/pytorch/pull/4950
