### ISSUE TITLE
Create/Reinstate distribution implementations available in PyTorch

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#699]
The following distributions are currently in the process of being migrated to PyTorch. In the interest of switching to using `torch.distributions` in Pyro with full broadcasting support, I suggest that we remove these distributions, which will make the switch easier. Creating an issue so that we reinstate these as soon as they are available in PyTorch master.

 - [x] poisson
 - [ ] half cauchy
 - [x] binomial

Additionally, we are retaining some distributions that are not yet migrated like `log_normal` and `multivariate_normal` (mostly because there are some tests/tutorials that rely on these), but will switch them to PyTorch as soon as they are available.

**Comment by fritzo** [comment]
`Binomial` is already in PyTorch master, but I'm fine removing the old implementation before we write a wrapper.

**Comment by neerajprad** [comment]
@jpchen - Assigning this to you for half-cauchy whenever that is available in PyTorch.

**Comment by neerajprad** [comment]
Actually, let us close this and track the integration as part of #606.

**Comment by jpchen** [comment]
halfcauchy needs to be reimplemented per discussion [here](https://github.com/pytorch/pytorch/pull/4771)
