### ISSUE TITLE
Changes to tracegraphELBO to support arbitrary batch dims

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#712]
I am trying to deprecate `batch_log_pdf` in distributions and have a single `log_prob` with the same batching semantics as PyTorch distributions, i.e. supporting arbitrary batch shape. I am finding that the air tutorial breaks at the following lines for #710:

```py
    for node in topo_sort_guide_nodes:
        node_log_pdf_key = 'batch_log_pdf' if node in guide_vec_md_nodes else 'log_pdf'
        downstream_costs[node] = model_trace.nodes[node][node_log_pdf_key] - \
            guide_trace.nodes[node][node_log_pdf_key]
        nodes_included_in_sum = set([node])
        downstream_guide_cost_nodes[node] = set([node])
        for child in guide_trace.successors(node):
            child_cost_nodes = downstream_guide_cost_nodes[child]
            downstream_guide_cost_nodes[node].update(child_cost_nodes)
            if nodes_included_in_sum.isdisjoint(child_cost_nodes):  # avoid duplicates
                if node_log_pdf_key == 'log_pdf':
                    downstream_costs[node] += downstream_costs[child].sum()
                else:
                    **downstream_costs[node] += downstream_costs[child] ** errors here
                nodes_included_in_sum.update(child_cost_nodes)
```

throwing an error, 
<details>
<summary> Error trace </summary>

```
Traceback (most recent call last):
  File "/Users/npradhan/workspace/pyro_dev/pyro/examples/air/main.py", line 328, in <module>
    main(**vars(parser.parse_args()))
  File "/Users/npradhan/workspace/pyro_dev/pyro/examples/air/main.py", line 215, in main
    loss = svi.step(X, args.batch_size, z_pres_prior_p=partial(z_pres_prior_p, i))
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/tracegraph_elbo.py", line 257, in loss_and_grads
    loss += self._loss_and_grads_particle(weight, model_trace, guide_trace)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/tracegraph_elbo.py", line 291, in _loss_and_grads_particle
    model_trace, guide_trace,  model_vec_md_nodes, guide_vec_md_nodes, non_reparam_nodes)
  File "/Users/npradhan/workspace/pyro_dev/pyro/pyro/infer/tracegraph_elbo.py", line 62, in _compute_downstream_costs
    downstream_costs[node] += downstream_costs[child]
RuntimeError: The expanded size of the tensor (3) must match the existing size (50) at non-singleton dimension 1
```

</details>

Upon investigating, I found that the reason this error is thrown is that it tries to sum up the `batch_log_pdf` for `node` and `child` which have shapes `(60, 3)` and `(60, 5)`. Our `batch_log_pdf` implementation just preserves the leftmost dimension, and hence the shape of the pdf score was `(60, 1)` for both of these sites and they could be summed up. With our new batching semantics, there is no concept of a single batch dimension and hence `log_prob` returns the same sized tensor* which cannot be summed up as earlier. Does this necessitate a change in tracegraphELBO, or is there a correct way of handling this inside AIR? 

cc. @fritzo, @martinjankowiak, @null-a.

\* for this distribution there is no `event_dim`, hence the shape of the scored tensor remains the same.

**Comment by null-a** [comment]
> Does this necessitate a change in tracegraphELBO, or is there a correct way of handling this inside AIR?

I'm not super familiar with all of the recent changes, but my guess is that trace ELBO will need teaching about the new batching scheme, since within an `iarange` it tracks the log prob of each data point separately, and the assumption it currently makes to do this (about the first dimension representing the batch) sounds like it no longer holds. I'm happy to help if I can, but I'm sure @fritzo and @martinjankowiak have a much better handle on this than me.

**Comment by martinjankowiak** [comment]
yeah we'll take a look at this. it might be a bit hairy. it might also be a bit before i have the time

**Comment by neerajprad** [comment]
@martinjankowiak, @fritzo - In case it helps you debug with a smaller example, the Rao blackwellization test - `test_vectorized_map_data_in_elbo_with_superfluous_rvs` also fails with the same error.
