### ISSUE TITLE
Add support for inverse and logdet in MultivariateNormal distribution

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#716]
In spare Gaussian Process models, we use "Woodbury matrix identity" and "matrix determinant lemma" to compute matrix inverse and logdet (unless we have to compute Cholesky decomposition of a high dimensional covariance matrix, which is computationally ineffective). Assume we already compute them, there should have a mechanism to put these results into the distribution. In the current implementation, we also use them to calculate log probability. So I think that we might mark them `lazy_property` as is `scale_tril`.

**Comment by fritzo** [comment]
cc @tbrx

This sounds reasonable. Note that we'll be switching to Brooks' new implementation in PyTorch soon https://github.com/probtorch/pytorch/pull/52, so we should try to make the changes upstream if possible.

**Comment by fehiepsi** [comment]
@fritzo @tbrx Sorry if I make any confusion (due to my wrong understanding of sparse implementations). The computation for the inverse is of O(N^2M) while the sparse methods only require O(NM^2) (actually, we do not compute the inverse, instead we compute Mahalanobis term!). So I think we should not implement the inverse and logdet in the general Multivariate implementation.

By the way, I have wrapped the MultivariateNormal distribution to support sparse methods in the pull request #722.
