### ISSUE TITLE
DMM Example  Model and guide dims disagree when IAF is applied

### ISSUE THREAD

**Issue by Algomancer** [uber/pyro#721]
When the number of IAF is non zero, the latent dimension changes to the same value as the batch size.

**Comment by martinjankowiak** [comment]
what version of pyro? what version of pytorch?

**Comment by Algomancer** [comment]
dev branch pyro (as of 16 hours ago), master pytorch

**Comment by neerajprad** [comment]
I tried fixing this, and I think we will need @fritzo's changes from https://github.com/pytorch/pytorch/pull/4937 to make it work.
