### ISSUE TITLE
Automatic grouping of variables

### ISSUE THREAD

**Issue by jpchen** [uber/pyro#73]
Based on discussions with @stuhlmueller, blocking/exposing variables needs some way to group variables together
[Example](https://github.com/uber/pyro/blob/ast-char-rnn/examples/char-rnn.py#L284) of manually constructing names to expose them.

From chat:
i think (3) would be pretty easy to address without a general solution for automatic naming
for example, suppose you could tag `sample`/`observe` statements like `sample("char_123", dist, tag="char")` and then later call `block(model, expose={"tags": ["char"]})`, or something like that

Related to #49, #37

**Comment by eb8680** [comment]
Added in #1159 and forgot to close this
