### ISSUE TITLE
Support constrain_to=___ argument in pyro.param()

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#749]
The usual way to do constrained optimization in Pyro is to transform unconstrained parameters, e.g.
```py
log_variance = pyro.param("log_variance", Variable(torch.zeros(10), requires_grad=True))
variance = log_variance.exp()
```
PyTorch 0.4 introduces a generic way to do this using `transform_to()`:
```py
from torch.distributions import constraints, transform_to

variance = transform_to(constraints.positive)(pyro.param("unconstrained_variance", ...))
```
It would be nice to use `transform_to()` to provide more first-class support for constraints in `pyro.param`, something like
```py
# possible future syntax:
variance = pyro.param("variance", Variable(...), constrain_to=constraints.positive)
```

See also discussion in #702

**Comment by fritzo** [comment]
@eb8680 I've attempted to implement this a couple of different ways (directly in the `ParamStore`, or as a poutine), but both were foiled by our use of `site['value']` to discover active params.

Could we pair code on this next week to see if there's a path forward? In particular I'd like to determine if we need any breaking changes to the `ParamStore` before 0.2 release, even if this feature doesn't make the 0.2 release.

**Comment by eb8680** [comment]
> Could we pair code on this next week to see if there's a path forward?

Sure
