### ISSUE TITLE
Support PyTorch scalars

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#771]
PyTorch master now supports scalars. Pyro currently breaks with PyTorch master.

**Comment by fritzo** [comment]
I think this works now. We don't use scalars in all our examples, but many test and examples already use scalars.

**Comment by fritzo** [comment]
@fehiepsi Do you know whether your gp module supports scalars? I'm starting to use it and I noticed that your tutorial still uses 1-dimensional tensors like `variance = torch.Tensor([10])` rather than scalars like `variance = torch.tensor(10.0)`.

**Comment by fehiepsi** [comment]
@fritzo I think that it should be fine. We use `length_scale` with `X / length_scale` and `variance` to multiply with the final computation of covariance matrix. At some place we do `variance.expand(...)` but the behavior of this method is the same for both scalar and non-scalar tensor. I will fix if you detect any error related to scalar tensors.
