### ISSUE TITLE
Create a poutine or messenger to configure site['infer']

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#774]
It would be nice to have a poutine or messenger that could set `site['infer']` properties. Using this we could e.g. simplify the `enum_discrete` logic to first set `site['infer']['enumerate'] = 'sequential'` for all discrete sites, then use existing logic without `site_is_discrete`.

**Comment by fritzo** [comment]
@eb8680 Would you be up to implement this? I'm not sure how.

**Comment by eb8680** [comment]
@fritzo sure, I can do that
