### ISSUE TITLE
Current status of HMC?

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#779]
I found that HMC is an interesting topic so I am trying to learn it from the current implementation. Is there any example to see how it works?

In addition, is there any reason why we use notions such as `velocity verlet`, `z`, `r` instead of `leapfrog`, `q`, `p` as in the [main reference](https://arxiv.org/pdf/1206.1901.pdf) which the implementation mentions?

**Comment by eb8680** [comment]
I don't think there are any HMC-specific examples yet, but the interface is pretty simple and one of the existing examples (e.g. Bayesian regression) could easily be modified to use HMC.  Contributions welcome!

> In addition, is there any reason why we use notions such as velocity verlet, z, r instead of leapfrog, q, p as in the main reference which the implementation mentions?

The velocity Verlet integrator is slightly different from the leapfrog integrator; see e.g. the [Wikipedia page](https://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet) for details.

**Comment by fritzo** [comment]
> `velocity verlet`, `z`, `r` instead of `leapfrog`, `q`, `p`

I like @neerajprad's choice of `(z, r)`. I would find `(q, p)` confusing since it is also ubiquitously used to denote distributions in variational inference.

I think the unit tests are currently the best place to see how HMC works. Also take a look at #740

**Comment by fehiepsi** [comment]
@eb8680 @fritzo Thanks a lot for your answers. They are definitely very helpful to me. I will try to use HMC following the unit test.
