### ISSUE TITLE
Multivariate normal sampling

### ISSUE THREAD

**Issue by bmazoure** [uber/pyro#782]
When trying to sample from the MVN distribution:
``
x = pyro.sample("my_sample",dist.MultivariateNormal, mu,sigma)  
print(x)
``
However, instead of a FloatTensor Variable, it returns simply
``
MultivariateNormal()
``

Is this expected behaviour / how can we pyro.sample from the distribution for now?

Many thanks

**Comment by fritzo** [comment]
To sample from distribution objects, write
```py
x = pyro.sample("my_sample", dist.MultivariateNormal(mu,sigma))
print(x)
```

@jpchen Do you have an ETA on publishing documentation for the dev branch #547 so users can see this new idiom?

**Comment by jpchen** [comment]
this is not a change related to using dev, this is just about pyro semantics. there was an identical issue [here](https://forum.pyro.ai/t/train-error-in-loss-and-grads-in-bayesian-neural-net/71/3). see the usage in this [example](http://pyro.ai/examples/bayesian_regression.html).

sorry, been busy with other high priority work. we'll have versioning for documentation before our next release, though thats not related to this problem.

**Comment by fritzo** [comment]
@jpchen This issue was caused by obsolete documentation at http://pyro.ai. You and I updated docs from `pyro.sample("name", dist.normal, mu, sigma)` to `pyro.sample("x", dist.Normal(mu, sigma))`, but these changes are not yet published.
