### ISSUE TITLE
Test for HMC fail randomly

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#786]
In the current dev branch, when I tried to run `pytest tests/infer/mcmc/test_hmc.py::test_hmc_conjugate_gaussian` with `TEST_CASES  = TEST_CASES[:1]` (just test the first case among four cases) repeatedly about 10 times, the test failed. So I guess that: despite we already had `@pytest.mark.init(rng_seed=34)`, somehow the results still cannot be reproduced.

**Comment by neerajprad** [comment]
What is the pyro/pytorch versions you are on? Could you also paste the logs?

**Comment by fehiepsi** [comment]
@neerajprad I believe the bug is fixed in #785 . The reason for randomness is: we sample `r`s based on keys of a dict.

**Comment by neerajprad** [comment]
Thanks for fixing this in #785. For the records, the change was to iterate over the keys of the dictionary in order when sampling the momenta -
 https://github.com/uber/pyro/pull/785#discussion_r169121588.
