### ISSUE TITLE
Docker image for Pyro + PyTorch dev

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#793]
It would make it easier for users to install Pyro dev branch if we had a Docker image that included a PyTorch build.

**Comment by neerajprad** [comment]
@fritzo - We can use the install scripts from #898 for CPU. For GPU, docker images can still be built using the included docker files, but due to their large sizes (more than 5 gigs), it will be tough to maintain and host them.

**Comment by fritzo** [comment]
Closing now that we have CI wheels.
