### ISSUE TITLE
Memory leak due to cyclic references in Trace

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#798]
@karalets noticed memory growth when using Pyro.

We tracked the number of non-garbage-collected objects during SVI inference. We found that objects grow over iterations but are occasionally collected. This evidence points to a cyclic reference somewhere. Among the amassing objects were `Variable`s and  Pyro `Trace` objects, suggesting that the cyclic reference is either in Pyro internals or in the networkx `DiGraph` object from which `Trace` inherits.

**Comment by karalets** [comment]
And I am happy to report that the changes in #801 fix the memory leak that has been plaguing me for a month.
My garbage collection calls now safely report unique counts of Variables and memory consumption is constant across training. 

Very happy this is resolved, this bug caused me grief for a while. Fantastic effort @fritzo
