### ISSUE TITLE
Add a tutorial on batch shaping in Pyro 0.2

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#814]
Pyro 0.2 will have stricter batching requirements (after #806) to allow new features like parallel enumeration #742 and nested `iarange` #780. This will require more careful use of `pyro.iarange`, `TorchDistribution.reshape()` and `pyro.scope()` for masking. The tutorial should also cover how to write broadcastable PyTorch code, such as using `Ellipsis` as in `x[..., i, j]` and setting flexible `sample_shape` in sample statements.

**Comment by eb8680** [comment]
What about two smaller tutorials, one upstream in PyTorch on distribution batch shape semantics and one in Pyro about Pyro-specific features?

**Comment by ngoodman** [comment]
this is a great idea.

the tutorial should include a clear statement of when a function / block can be batched. (eg. it can't include certain operators which take a tensor to a non-tensor. other restrictions?)

**Comment by fehiepsi** [comment]
Didn't notice this thread. The tutorial will be greatly helpful! I have to spend a few days to work with Pyro distribution shape semantics and still not sure I make things right. :(
