### ISSUE TITLE
Remove networkx dependency from Trace

### ISSUE THREAD

**Issue by eb8680** [uber/pyro#818]
Having briefly tried and failed to fix the memory leak (#798) at its source, I propose rewriting `Trace` as a simplified custom object (effectively a dict of `OrderedDict`s) with an option to export to a networkx graph.

**Comment by fritzo** [comment]
Sounds reasonable. I'd like to hear your networkx war story.

**Comment by eb8680** [comment]
Will reopen if/when we revisit.
