### ISSUE TITLE
Clean up Trace API

### ISSUE THREAD

**Issue by eb8680** [uber/pyro#819]
After the refactor in #818, we should take the opportunity to remove the various idiosyncratic helper methods in `Trace` and replace them with a uniform functional API.

**Comment by fritzo** [comment]
This sounds great. It seems like the right level of granularity is sites (Trace nodes). So we could implement some functions that operate on sites, sometimes caching results in the sites, something like
```py
def site_batch_log_pdf(site):
    ...

def site_score_parts(site):
    ...
```

**Comment by eb8680** [comment]
Not super urgent, will reopen when we revisit.
