### ISSUE TITLE
Using multivariatenormal as the guide

### ISSUE THREAD

**Issue by pangard** [uber/pyro#850]
Hello:
I'm new to pytorch and pyro. It sure rocks, but we're trying to migrate some code form other projects and there was one show stopper.
Using a sequence of univariate normals as the guides is too restricting, isn't it?: we are imposing that the variables are not correlated a posteriori, whatever the data says.
Fortunately there is now on the dev branch a multivariatenormal, but it requires a semidefinite matrix, so in order to use it as a guide we need the equivalent of the softplus in the tutorial, if I got the Bayesian Regression tutorial right. I'm thinking of the matrix exponential (even the matrix softplus makes perfect sense), but I can't find an implementation of matrix exponentials in pytorch.
There might be other blockers also ...
Can anybody help?
Thanks
#166

**Comment by pangard** [comment]
theano does have matrix exponentials:

http://deeplearning.net/software/theano/library/tensor/slinalg.html

looking closely, they simply call scipy:

https://github.com/Theano/theano/blob/d395439aec5a6ddde8ef5c266fd976412a5c5695/theano/tensor/slinalg.py#L487-L515

So maybe it is just a matter of creating a pytorch module around that :-/ ???

**Comment by eb8680** [comment]
Hi, there is a multivariate normal distribution with a reparameterized sampler in dev.  If you want to use it in a guide you'll need to follow the instructions in the README for installing the dev version of Pyro.  If you want to parametrize the covariance directly, you can use [torch.distributions.transforms.LowerCholeskyTransform](http://pytorch.org/docs/master/distributions.html#torch.distributions.transforms.LowerCholeskyTransform) to construct a Cholesky factor and compute a covariance matrix from that.  These features are not yet in the release versions of Pyro and PyTorch, so the documentation is a bit sparse.

**Comment by pangard** [comment]
Thanks a lot, eb8680! Hadn't noticed the "reparameterized sampler". Will test it tomorrow...
