### ISSUE TITLE
requirement.txt

### ISSUE THREAD

**Issue by hongweizeng** [uber/pyro#851]
I think there is a need to add a **requirement.txt**.

**Comment by fritzo** [comment]
Can you be specific about the need you see? Unless there is a specific need, it will be easier to for us to maintain a single dependency list in `setup.py` than to duplicate that information to `requirements.txt`. Note that `setup.py` allows distinction between different types of dependencies and is more precise than a `requirements.txt`.

**Comment by neerajprad** [comment]
To add to what @fritzo said, if you need to pin down specific dependencies for your application (for replicability, other dependency interactions etc.), you are free to define your own `requirements.txt`. As a library, we would like to define the least constrained setup that different applications can re-use.

**Comment by hongweizeng** [comment]
thanks for your suggestions.
