### ISSUE TITLE
Error while installing pocketsphix in python 3.6

### ISSUE THREAD

**Issue by vinay047** [uber/pyro#853]
Hi,
Tried downloading with pip install pocketsphix but i am facing the below errors.
 
 swig.exe -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    error: command 'swig.exe' failed: No such file or directory 

Thanks in advance!!

**Comment by neerajprad** [comment]
Have you tried installing sphinx via [pip](http://www.sphinx-doc.org/en/stable/install.html#windows-install-python-and-sphinx)? While the recommended python version is 2.7, it seems to support python 3 as well. Note that `sphinx` is a dev dependency, and you do not need to install it to be able to use Pyro, but you will need it to run tests and contribute to the project.

Our installation and testing has mostly been limited to unix like systems, and you could face issues installing some dependencies on Windows. I would suggest opening issues like this on our [forum](http://forum.pyro.ai), to see if there are other Windows users who may be able to help.

**Comment by jpchen** [comment]
to add, if youre using windows i highly recommend using [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/) (this will probably make your life easier for other projects in the future as well)
