### ISSUE TITLE
Broadcasting issue with Gaussian Process

### ISSUE THREAD

**Issue by tobyclh** [uber/pyro#862]
I was trying to fit some 2D data with Gaussian Process.
During the training at multivariate normal, calculating log prob fails as broadcast doesn't work. 
adding unsqueeze followed by expand_as and diag seems to fix the issue.
Code to reproduced 
```py
#%%
import torch
import pyro
from pyro.contrib.gp.kernels import RBF
from pyro.contrib.gp.models import GPRegression
import pyro.distributions as dist
from pyro.infer import SVI
from pyro.optim import Adam
from pyro.util import ng_ones, ng_zeros

pyro.set_rng_seed(0)

N = [20, 500]
X = dist.Uniform(ng_zeros(N), ng_ones(N)*5).sample()
y = 0.5 * torch.sin(3*X) + dist.Normal(ng_zeros(N), ng_ones(N)*0.5).sample()

kernel = RBF(input_dim=500, variance=torch.Tensor([10]), lengthscale=torch.Tensor([10]))
gpr = GPRegression(X, y, kernel, noise=torch.Tensor([1]))


optim = Adam({"lr": 0.001})
svi = SVI(gpr.model, gpr.guide, optim, loss="ELBO")
losses = []
num_steps = 1000
for i in range(num_steps):
    losses.append(svi.step())
```

**Comment by tobyclh** [comment]
@eb8680 
master, dev branch of pytorch and pyro!
@fehiepsi 
I made a PR and tested it but I can't seems to get the pyro test system working so it would be nice if you can let me know whether it passes those tests (those tests fails even on dev branch for some reason)

**Comment by SINDHUKUMARIP** [comment]
from pyro.util import ng_ones, ng_zeros
ImportError: cannot import name 'ng_ones'

**Comment by eb8680** [comment]
@SINDHUKUMARIP this code snippet is now outdated and `ng_ones` and `ng_zeros` no longer exist in Pyro 0.2.1.  Please see the GP tutorial instead for up-to-date examples of GP usage: http://pyro.ai/examples/gp.html
