### ISSUE TITLE
Ask for structures for tutorials

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#874]
It would be great if Pyro examples page can have structures for sidebar like http://pytorch.org/tutorials/ or http://docs.pymc.io/examples.html. For example, if I want to add several tutorials on Gaussian Process, I will create a folder named Gaussian process and add several notebooks there.

**Comment by fritzo** [comment]
@jpchen Can you remind me where our tutorial index lives? In addition to making a tree structure, I'd like to add my brief GMM tutorial.

**Comment by fehiepsi** [comment]
@jpchen Could we make a tutorial structure like this:
http://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html

For example, we can wrap "SVI Part I", "SVI Part II", "SVI Part III" under "Introduction to SVI".

**Comment by jpchen** [comment]
@fehiepsi i discussed this with @fritzo and was convinced that having a flat directory structure was easier to maintain since we dont have that many tutorials. do you have a reason to nest them in directories?

**Comment by fehiepsi** [comment]
My only reason is to group tutorials related to Gaussian Process into a directory. However, it is unnecessary to have directories now because we just have one tutorial on that topic. So it is better to open this issue again at some point in the future. No need to worry about it now. :D
