### ISSUE TITLE
Inefficient asymptotic scaling in TraceGraph cost computation

### ISSUE THREAD

**Issue by eb8680** [uber/pyro#88]
I merged #81 so I'm opening an issue for the problems raised in [this discussion](https://github.com/uber/pyro/pull/81/#discussion_r135055003).

Briefly, according to @null-a the problem is that computing the downstream costs with the current approach may not scale linearly with the number of choices, even though it should theoretically.  The following model is meant to illustrate this:
```python
n = 200

def model():
    for i in range(n):
        pyro.sample('x{}'.format(i), Bernoulli(Variable(torch.Tensor([0.5]))))

def guide():
    for i in range(n):
        p = pyro.param('p{}'.format(i), Variable(torch.FloatTensor([0]), requires_grad=True))
        pyro.sample('x{}'.format(i), Bernoulli((sigmoid(p))))
```

**Comment by eb8680** [comment]
@null-a @martinjankowiak can this be closed?

**Comment by null-a** [comment]
Yes, I think so. IIRC the scaling could only be improved for specific cases, for the general case the current implementation is probably as good as it gets. I'll close this, and let @martinjankowiak re-open if I've mis-remembered.
