### ISSUE TITLE
Analytic KL divergences

### ISSUE THREAD

**Issue by karalets** [uber/pyro#91]
I suggest (also discussed this before in many meetings and lately with @martinjankowiak ) that we add a set of analytical KL-divergences for every type of distribution we have.

We could use those to do something I call local inference, i.e. at each variable fully integrate out the local KLdiv analytically if possible. This can be done in the normal klqp but is an even better fit to the tracegraph klqp.

Specifically, within elbo at each site for a reparametrized distribution (simplest case) we do the operation:  score += log_pdf_p - log_pdf_q

We could change that to be:
score +=  kldiv(dist.q, dist.p )

The elbo-math allows for that just fine because it decomposes and we reduce some variance.

Also, the way I envision this working is with distribution names. Currently, the names of the distributions only appear as class-names, maybe we could keep around name-fields as well that are easier to check.

One can also think of a smart version of a kldiv method which does the following:
0. "Analytical kldiv" is a prototype function.
1. It receives two distributions as input, gets their parameters and types of distributions (i.e. via dist.name which we currently do not use)
2. If they are of the same type and the kldiv has an analytical expression for that type available, it uses that expression
3. if they are of a different type or analytical expression is otherwise unavailable it draws a specified number of samples and calculates the explicit log-ratio. One can also make that sampler clever (i.e. quadrature). This reverts to the elbo trace-samples in the single-sample case.
Note: when using more samples this is distinct from the number of samples for the entire elbo, since these here are just samples conditioned on all previous variable states to evaluate the local kldiv, not to populate a trace. It is probably not efficient to use quadrature here.

Is a good place for the kl-divergences the util.py in your opinions?

I can sketch such a prototype with an expression for the simple gaussian case and would try it in the normal elbo estimator. @martinjankowiak  wants to use this in his graph-klqp to reduce variance further.

@martinjankowiak, does this outline make sense to you for your use-case?

**Comment by eb8680** [comment]
@fritzo should this issue live upstream with distributions?

**Comment by fritzo** [comment]
Correct, moving this issue to https://github.com/probtorch/pytorch/issues/37
