### ISSUE TITLE
GP tutorial failing distributions argument validation check

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#927]
From #922, `gp.ipynb` fails when we run pyro with distributions argument validation enabled as the `Kfdiag` term can be negative for some indices resulting in us passing a negative value for variance for Normal. Let us fix this and re-enable the `pyro.set_validation(True)` statement for the tutorial.

**Comment by neerajprad** [comment]
cc. @fehiepsi

**Comment by fehiepsi** [comment]
Confirmed. I printed the min value of Kfdiag and saw that the tutorial throw many (small ~ -1e-6) negative values. This should be related to a precision issue.

**Comment by neerajprad** [comment]
@fehiepsi pointed out that this is a precision related issue, and goes away once we increase the value of `jitter`.
