### ISSUE TITLE
Dev docs are broken on pyro.ai

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#931]
Currently this page is blank http://docs.pyro.ai/en/dev/primitives.html
even though docs correctly build locally.

**Comment by fritzo** [comment]
@jpchen Do you think this could be a pytorch wheel mismatch when docs are built?

**Comment by jpchen** [comment]
the logs confirm your hunch, we need to upgrade to the new pytorch wheel. @neerajprad did you bake a new wheel we can use?

**Comment by fritzo** [comment]
@neerajprad IIRC we use some special grepping to pull out the blessed commit from README.md when we build a docker or something. Can we use the same technique to automatically grab the latest wheel when generating docs on readthedocs (inside JP's doc generation script)?

**Comment by neerajprad** [comment]
> Can we use the same technique to automatically grab the latest wheel when generating docs on readthedocs (inside JP's doc generation script)

Could you point me to the code that does this? Can we just run `bash scripts/install_pytorch.sh` to install pytorch (that would do the grepping)?

**Comment by fritzo** [comment]
Thanks for fixing this, @jpchen
