### ISSUE TITLE
Empirical distribution for MCMC

### ISSUE THREAD

**Issue by neerajprad** [uber/pyro#942]
As sketched in #655 (but not merged), this is to have an empirical distribution with a limited scope (mentioned below). Amongst other possible use cases, this will be useful as a convenience utility for MCMC algorithms. For instance, to not require end users to have to manipulate traces. e.g. from HMC tests:

```
    for trace, _ in mcmc_run._traces(data):
        posterior.append(trace.nodes['p_latent']['value'])
```

 - The aim is to hold a collection of data, and assess the statistical properties of the sample, e.g. mean, median, variance, etc. Scoring additional samples via `log_prob` is not supported due to computational reasons (while we can do some binning and log prob computation, for most real (even toy sized) problems, this will be very expensive. e.g. `torch.histc` only supports histograms for scalars).
 - Samples are all tensor values.

**Comment by fritzo** [comment]
@eb8680 Would this help at all with our factor graph work #915 ? E.g. we could construct a set of Histograms, each marginalized down to a single site?

**Comment by eb8680** [comment]
> Would this help at all with our factor graph work

Yeah, I was just talking to @neerajprad about this since I was working on something similar this afternoon.  We should add a section to the design doc for it.

**Comment by neerajprad** [comment]
> We should add a section to the design doc for it.

Sounds great! Lets sync up on this.
