### ISSUE TITLE
Update to latest PyTorch which does type inference in torch.tensor()

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#944]
As of https://github.com/pytorch/pytorch/pull/5997, `torch.tensor` cares about whether its args are floats or ints:
```py
>>> torch.tensor(0).type()
'torch.LongTensor'
>>> torch.tensor(0.).type()
'torch.FloatTensor'
```
This violates our assumptions in both testing and initialization.

**Comment by neerajprad** [comment]
The bigger problem that I see is that it does not do any type casting when you would expect it to. See below. 

```
>>> import torch
>>> t = torch.tensor([0, 1])
>>> u = torch.tensor([0.0, 1.0])
>>> u * t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'
```

Or, even int to long:
```
>>> t = torch.tensor([0, 1], dtype=torch.int32)
>>> u = torch.tensor([0, 1], dtype=torch.int64)
>>> u * t
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected object of type torch.LongTensor but found type torch.IntTensor for argument #2 'other'
```

This could require a lot of changes in the code, but before undertaking that, is this really the designated behavior for the next release?

**Comment by fritzo** [comment]
@gchanan Has PyTorch casting behavior settled down to the point where we should update Pyro, or should we hold off for a week? (Thanks for the heads up BTW!)

**Comment by neerajprad** [comment]
From @colesbury on slack:

> We plan to support at least some implicit type casting. I don't think we supported it previously, though

I suppose I noticed this now because a lot of our tensors are now getting converted to long instead of floats.

**Comment by gchanan** [comment]
@fritzo @neerajprad there are a few different things going on here:
1) type inference: `torch.tensor` and `variable` now do type inference based on the data, like `np.array` does; this is probably what @neerajprad is referring to and we aren't planning to make any changes there.  See PR: https://github.com/pytorch/pytorch/pull/5997
2) type casting: @apaszke is working on this over in PR: https://github.com/pytorch/pytorch/pull/5864; this is the "you would expect it" case and you can (probably) work around it now by doing the casting yourself, but it might be easier just to wait.

**Comment by neerajprad** [comment]
Thanks, @gchanan! Looking forward to seeing https://github.com/pytorch/pytorch/pull/5864 in master.

**Comment by gchanan** [comment]
For fixing 1., if you want a tensor of the default (floating) type, make sure the data has a floating element, i.e. do torch.tensor(1.) instead of torch.tensor(1).

**Comment by neerajprad** [comment]
> For fixing 1., if you want a tensor of the default (floating) type, make sure the data has a floating element, i.e. do torch.tensor(1.) instead of torch.tensor(1).

Thanks, @gchanan. We were planning to do exactly that. We have a bunch of tensors which were earlier `float` but are now being inferred as `long` without the `.`.
