### ISSUE TITLE
Feature request: display ADVI params

### ISSUE THREAD

**Issue by slaweku** [uber/pyro#973]
Hi,
When using ADVI guide, it is possible to print nicely a sample of the model parameters, with e.g.
print(advi.guide(y))
Pyro's param store contains advi_loc and advi_scale/advi_scale_tril, but it is not clear which parameter refers to which index of these vectors/arrays and, from what I understand, these are unrestricted params, not my models restricted params I care about.
So, I would like to request adding a functionality for a nice display of the means of location and scale of the model parameters.

Slawek

**Comment by fritzo** [comment]
I think the easiest interface would be to expose quantiles, e.g. `.median()`. Some of these parameters are transformed, and it's not obvious how to interpret e.g. the variance of a normal distribution that is then transformed via sigmoid transoform to lie in `[0,1]`. I'll expose `.median()` first.
