### ISSUE TITLE
Attend, Infer, Repeat: fuzzy output

### ISSUE THREAD

**Issue by jthsieh** [uber/pyro#977]
Thanks for providing the AIR tutorial!
I followed the AIR tutorial and tried implementing a simpler model. I fix the number of digits to 2, so I don't need `z_pres` and `baseline`. I'm able to get really good results. The digits are very well separated and the digit locations look accurate. However, the output images are a little fuzzy and dim.

Input:
<img width="67" alt="screen shot 2018-04-06 at 3 47 38 pm" src="https://user-images.githubusercontent.com/9127118/38447408-f3f5e088-39b1-11e8-8d4f-478517aed723.png">
Output:
<img width="66" alt="screen shot 2018-04-06 at 3 47 48 pm" src="https://user-images.githubusercontent.com/9127118/38447411-f83eda28-39b1-11e8-8f84-01d2aa8d0991.png">

So, when I calculate the Binary Cross-Entropy, I get a really high number. Here are my questions:

- What might be the cause of this? (I'm relatively new to SVI.) Can it be the ELBO objective, the standard deviation 0.3 of the Gaussian likelihood, or something else?
- Why does the tutorial add all the objects together (in `prior_step `). I think that doesn't make sense, since the added image might be > 1 if there is overlap. So I use `max` instead of `sum` in my code.

**Comment by eb8680** [comment]
cc @null-a

**Comment by null-a** [comment]
> What might be the cause of this?

Do you think these are fuzzier/dimmer than the [reconstructions shown](http://pyro.ai/examples/_static/img/air/reconstructions.png) in the tutorial? If so that seems to rule out the ELBO and likelihood, and suggests your implementation maybe doing something different? Or could it be as simple as optimisation needs to run for longer?

> Why does the tutorial add all the objects together (in prior_step)

IIRC that's the approach described in the paper, and I was trying to be faithful to that. Given that digits don't overlap in the dataset, there's perhaps not too much difference in the approaches?

**Comment by jthsieh** [comment]
Thank you! The quality indeed gets better the longer I run, so I'll leave it at that.

One more question (sorry I'm new to pyro). I'd like to add a loss term in addition to ELBO, for example L2 norm on some latent variables, or even a discriminator. How can I do that?

**Comment by null-a** [comment]
> Thank you! The quality indeed gets better the longer I run, so I'll leave it at that.

No problem, that's great to hear.

> I'd like to add a loss term in addition to ELBO
> How can I do that?

I'm afraid I don't know how best to do this either, but hopefully someone more knowledgeable will chime in and point you in the right direction.
