### ISSUE TITLE
Remove circular dependencies before 0.2 release

### ISSUE THREAD

**Issue by fritzo** [uber/pyro#981]
Proposed module organization to avoid circular dependencies:
1. avoid importing `a/b/__init__.py` from any sibling module `a/b/c.py`
2. try to maintain the following low-to-high level import order:
  `distributions < param < { poutine, ops, nn } < pyro < infer < contrib`
3. avoid explicit mutual imports between pairs of modules.

**Comment by eb8680** [comment]
Is there any way to check for circular dependencies automatically?  Can we add that to our CI suite?

**Comment by fritzo** [comment]
Pycycle seems to say we're clean:
```sh
$ pycycle --source pyro/
Target source provided: /Users/fritzobermeyer/github/uber/pyro/pyro
Project successfully transformed to AST, checking imports for cycles..
No worries, no cycles here!
If you think some cycle was missed, please open an Issue on Github.
Finished.
```

**Comment by eb8680** [comment]
Does that mean this can be closed?
