### ISSUE TITLE
Learn pyro.module's parameters outside model/guide

### ISSUE THREAD

**Issue by fehiepsi** [uber/pyro#995]
At the current state, `pyro.optim` just learns parameters of an nn.Module if it is registered by `pyro.module` inside model/guide pair. It would be nice if we can do something like this:

```
def Net(nn.Module):
    ...

net = pyro.module("net", Net())
def model(x, y):
    o = net(x)
    pyro.sample("y", dist.Normal(o, 1), obs=y)

def guide(x, y):
    pass

optimizer = optim.Adam({})
svi = SVI(model, guide, optimizer, "ELBO")
```

At the current state, we have to do as follows
```
net = Net()
def model(x, y):
    pyro_net = pyro.module("net", net)
    o = pyro_net(x)
    ...
```

**Comment by eb8680** [comment]
Hmm, I'm not sure about having an inference algorithm update parameters that never appear in `param` statements in its model.  In the example snippet, why not just lift the `Module` with `lambda`?: `lambda x: pyro.module("net", net)(x)`

**Comment by fehiepsi** [comment]
This is useful when we build a model which does not know ahead its name and its type. Of course, we can use `if else` to handle function/nn.Module but don't you think that it is too verbose?

**Comment by eb8680** [comment]
> This is useful when we build a model which does not know ahead its name and its type

But in that case you should be able to use the `lambda` pattern I suggested, no `if`/`else` required

**Comment by fehiepsi** [comment]
Yeah, you save my day! :D I spent a lot of time to debug codes before recognizing that svi does not learn params outside of its scope and ended with that pull request... Thanks!

**Comment by PineappleLee** [comment]
If you lift the Module with lambda?: lambda x: pyro.module("net", net)(x), the program would thought it a expression, it is not a Module anymore, so the optimimizer couldn't learns parameters.

**Comment by PineappleLee** [comment]
If you lift the Module with lambda, like lambda x: pyro.module("net", net)(x), the program would thought it a expression, it is not a Module anymore, so the optimimizer couldn't learns parameters.
